### ISSUE TITLE
Default to 0.0.0.0?

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#1010]
Right now `quickwit service run searcher` listens to 127.0.0.0 by default.

This can be confusing for the user.
Fortunately, the logs are quite helpful for the user who knows what to look for.

Should we default to 0.0.0.0?

**Comment by fulmicoton** [comment]
@fmassot @guilload

**Comment by guilload** [comment]
There are two perspectives:
- The ease of use perspective, you want `0.0.0.0`
- The security perspective, you want `127.0.0.1` to restrict access by default, users explicitly setting the listen address to `0.0.0.0` are basically telling you "I acknowledge you're trying to protect me but I know what I'm doing and I won't be angry at you if I screw up."

The webservers I know (gunicorn, sanic) default to `127.0.0.1`. Meilli does too. Materialize went for `0.0.0.0`.

We should at least reinstate the --ip / --port options to override the default config value.

**Comment by fulmicoton** [comment]
Agreed.

Cassandra and postgresql default to 127.0.0.
I suggest we just try to mitigate user pain.

For instance, we could add a very visible warning when the user uses 127.0.0.0
and set some peer seeds for instance with a host != localhost.

We can probably always display some log line explaining the server will only be accessible locally, etc.
