### ISSUE TITLE
Missing doc

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#1019]
- Document the file source parameter refresh hash tag thing
- Document the kafka conf
- Document that the non musl binary requires libpq to be installed on your system, and the name of the packaged for RPM / deb systems.

**Comment by guilload** [comment]
For 2. This will be part of the source config page. [Preview on Notion](https://www.notion.so/Source-configuration-186cbd8889864b2a8aa5721959963376).

**Comment by fmassot** [comment]
For 3, we have something here: https://github.com/quickwit-inc/quickwit/blob/main/docs/getting-started/installation.md#note-on-external-dependencies

**Comment by evanxg852000** [comment]
We don't currently make `.rpm` nor `.deb` packages though.
Might be a good time to add those.

**Comment by fmassot** [comment]
Let's sum up things

- [ ] (Done on Notion, waiting for merge in main) Document the file source parameter refresh hash tag thing
- [ ] (Done on Notion, waiting for merge in main) Document the kafka conf
- [x] Already merge Document that the non musl binary requires libpq to be installed on your system,

I removed the  RPM / deb systems from the list.

**Comment by evanxg852000** [comment]
> @evanxg852000 can you open an issue on that? I think we will do that a little bit later (maybe after 0.4)
https://github.com/quickwit-inc/quickwit/issues/1036
