### ISSUE TITLE
Handle single bound time interval

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#104]
User should be able to search on interval with a single bound `t > start_time` instead of being forced to define an entire interval.

**Comment by evanxg852000** [comment]
Looking at [this](https://github.com/quickwit-inc/quickwit/blob/main/quickwit-search/src/lib.rs#L84-L85), I am thinking two ways here:
- having `extract_time_range` return ranges like `i64::MIN..t` or `t..i64::MAX` and handle this internally in `Metastore::list_splits()`
- extract_time_range return a tuple of `(t, None)` or `(None, t)` and change `Metastore::list_splits()` interface to 
```rust
list_splits(
        &self,
        index_id: &str,
        split_state: SplitState,
        start_time: Option<i64>,
        end_time: Option<i64>,
    )
   ```
   If I understand your comment we are leaning towards the second option?

**Comment by evanxg852000** [comment]
Another option is to use 
```rust
list_splits(
        &self,
        index_id: &str,
        split_state: SplitState,
        time_range: (Bound<i64>, Bound<i64>)
    )
```

**Comment by fulmicoton** [comment]
I like your solution 1.
