### ISSUE TITLE
Do we need to set kafka autocommit to false [Question]

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#1070]
In librdkafka, autocommit is set to true by default.
Shouldn't we set it to false?

https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

**Comment by guilload** [comment]
We do:
https://github.com/quickwit-inc/quickwit/blob/main/quickwit-indexing/src/source/kafka_source.rs#L357

From our docs:
> Note that the Kafka source manages commit offsets manually thanks to Quickwit’s index checkpoint mechanism and always disables auto-commit.

See also:
- Manual Partition Assignment
- Storing Offsets Outside Kafka

> Each record comes with its own offset, so to manage your own offset you just need to do the following:
>
> Configure enable.auto.commit=false
> Use the offset provided with each ConsumerRecord to save your position.
> On restart restore the position of the consumer using seek(TopicPartition, long). 

https://kafka.apache.org/28/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html

**Comment by fulmicoton** [comment]
Awesome!
