### ISSUE TITLE
build failing on m1 Mac

### ISSUE THREAD

**Issue by galactus009** [quickwit-inc/quickwit#1104]
When trying to build on m1 Mac the build is failing with below errors

quickwit-0.2.0 %  RUST_BACKTRACE=1 cargo build
   Compiling quickwit-cli v0.2.0 (/Users/ayalar/quickwit-0.2.0/quickwit-cli)
   Compiling num_cpus v1.13.1
   Compiling parking_lot_core v0.8.5
   Compiling signal-hook-registry v1.4.0
   Compiling socket2 v0.4.2
   Compiling cpufeatures v0.2.1
   Compiling which v4.2.2
   Compiling time v0.1.44
error: failed to run custom build command for `quickwit-cli v0.2.0 (/Users/ayalar/quickwit-0.2.0/quickwit-cli)`

Caused by:
  process didn't exit successfully: `/Users/ayalar/quickwit-0.2.0/target/debug/build/quickwit-cli-2647c80d0bef984e/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'byte index 7 is out of bounds of ``', quickwit-cli/build.rs:28:27
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
     1: core::panicking::panic_fmt
               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
     2: core::str::slice_error_fail
     3: core::str::traits::<impl core::slice::index::SliceIndex<str> for core::ops::range::RangeTo<usize>>::index
               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/str/traits.rs:289:21
     4: core::str::traits::<impl core::ops::index::Index<I> for str>::index
               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/str/traits.rs:64:9
     5: <alloc::string::String as core::ops::index::Index<core::ops::range::RangeTo<usize>>>::index
               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/string.rs:2228:10
     6: build_script_build::main::{{closure}}
               at ./build.rs:28:27
     7: core::result::Result<T,E>::map_or
               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:793:22
     8: build_script_build::main
               at ./build.rs:23:27
     9: core::ops::function::FnOnce::call_once
               at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
error: build failed

 quickwit-0.2.0 % 

 quickwit-0.2.0 % rustc --version
rustc 1.57.0 (f1edd0429 2021-11-29)

 quickwit-0.2.0 % cargo --version
cargo 1.57.0 (b2e52d7ca 2021-10-21)

**Comment by fmassot** [comment]
Thanks @galactus009 for reporting this bug. I have a M1 and I was working on cargo 1.56, everything worked well with 1.56.

I've just updated cargo/rustc to 1.57 and I had a couple of minor issues, there are formatting errors that are now raised with the new version of cargo. I will fix that.

But I did not reproduced the error "thread 'main' panicked at 'byte index 7 is out of bounds of ``', quickwit-cli/build.rs:28:27".
Can you make a cargo clean first? And while I fix the bugs on 1.57, you can try with cargo 1.56.

**Comment by galactus009** [comment]
hello

I am getting same error even after downgrading to 1.56
quickwit-0.2.0 % cargo --version           
cargo 1.56.0 (4ed5d137b 2021-10-04)
quickwit-0.2.0 % rustc --version                                     
rustc 1.56.1 (59eed8a2a 2021-11-01)

 % cargo clean && cargo build
(o/p truncated)
   Compiling spin v0.9.2
error: failed to run custom build command for `quickwit-cli v0.2.0 (/Users/ayalar/quickwit-0.2.0/quickwit-cli)`

Caused by:
  process didn't exit successfully: `/Users/ayalar/quickwit-0.2.0/target/debug/build/quickwit-cli-4d3090bba1777188/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'byte index 7 is out of bounds of ``', quickwit-cli/build.rs:28:27
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

**Comment by fmassot** [comment]
Mmm, ok I think I understood, it's not directly related to quickwit code. The faulty code is as follows:
```rust
let git_commit_hash = Command::new("git")
    .args(&["rev-parse", "HEAD"])
    .output()
    .map_or("unknown".to_string(), |output| {
        let hash = String::from_utf8(output.stdout).unwrap();
        String::from(&hash[..7])
      });
```

Can you tell me the output of the following command `git rev-parse HEAD`?

**Comment by galactus009** [comment]
Hello

apologies. I downloaded the zip file then the build was failing. but when I git cloned v0.2.0 tag and built it worked fine.
Sorry for the rehearing
