### ISSUE TITLE
IndexDataParams.temp_dir is actually not a temp dir.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#115]

**Comment by evanxg852000** [comment]
What relation do we expect from `IndexDataArgs::temp_dir` or is it a working directory?
My understanding was that we wanted to keep this folder afterward. If the real intent is just to have a temporary directory to work with the we probably need to think of droping the `temp-dir` flag. and relying on `temdir` to give us one.

**Comment by evanxg852000** [comment]
I reassigned to you @fulmicoton  since you already coded it in your PR. But my question still remains. What's the use of having it as a command line parameter when we are going to wipe it at the end anyway?

**Comment by fulmicoton** [comment]
We need a temp directory to build our split. This directory needs to be deleted as soon as possible, because 
- the more we wait the likely it is that deleting the directory will fail
- the more we wait the more we use hard disk space.

The temp directory of the OS is generally speaking a decent location for this.
If we end not being able to remove our files, it is clear to the user adn the OS that the content can be deleted safely.
This is a very good default.

But the tempdir can be based on tmpfs, and the user may prefer us to use a directory on a specific disk.
For this reason the user can pass an argument targetting the destination. We can still rely on tempfile::TempDir to handle this directory, in order to use RAII for its deletion. (This is unfortunately not bulletproof)
