### ISSUE TITLE
Implement the meta store interface and its impl for its file-backed implementation

### ISSUE THREAD

**Issue by guilload** [quickwit-inc/quickwit#12]
# Purpose and Challenge

Quickwit needs a way to keep track of the list of splits available for a given index. Currently the metastore's implementation is backed by PostGreSQL.

However, deploying PostgreSQL might be a cumbersome requirement for the user who just wants an index for a single large static dataset in their datalake, or who wants to test out whether Quickwit's search is working as advertised before throwing themselves into deploying multiple services.

For this reason, there will be different implementation of the datastore, the most constrained one, being stored directly on S3.

# API Definition

## Functional need

- Indexer need to publish the splits they have finished building.
- Searcher need to list the splits in an index, possibly pruning them based on some metadata.
- Mergers need to publish the outcome of a merge, (generally the atomic publication of a split and the deletion of some other).
- Retention manager need to be able to remove split based on their timestamps (and possibly some metadata?).

Note that some of these operation imply some interaction with the storage. This is not the role of the meta store, and the correct implementation of its client application is assumed. The meta store semantics however, need to make this coordination possible... (See section below)

## File management need, and the split lifecycle

Quickwit needs a way to ensure that we can cleanup unused files, and this process needs to be resilient to any fail-stop failures.

Because our metastore are typically more constrained than a filesystem (e.g.: object storage), we cannot rely in a write ahead log. We do not want to rely on a strategy that would require to list the files in the store as well, because:
- we might end up removing some user file non related with quickwit.
- listing files is notoriously slow and clumsy on object storage.

Instead, we rely atomically shifting the status of splits.

A split goes into the following lifecycle

```
Building
   -stage->
Staged
   -publish->
Published
   -markAsDelete->
MarkAsDeleted
   -delete->
Deleted
```

Building splits and deleted splits are not states that are registered in the metastore, and should have no durable left-over anywhere.

We maintain the following invariant:
If a split has a files in the storage, it MUST be registered in the meta store, and its state can be either
- Staged:  the splits is almost ready. Some of its files may have been uploaded in the storage.
- Published: the splits is ready and published.
- ScheduledForDelete: the split is scheduled to be deleted.

**Before** creating any file, we need to stage the split. If there is a failure, upon recovery we schedule for delete all of the staged splits.

**A client may not necessarily remove file from storage right after marking it as deleted.** A CLI client may delete files right away, but a more serious deployment should probably only delete these files after a period of time to give some time to running search queries to finish.

# API Definition

## Stage splits (W)

```rust
/// Stages a splits.
/// A split needs to be staged BEFORE uploading any of its files to the storage.
/// The SplitId is returned for convenienced but it is not generated
/// by the metastore. In fact it was supplied by the client and is present in the split manifest.
fn stage_split(split_manifest: SplitManifest) -> Result<SplitId, StageError>;

enum StageError {
    InvalidManifest(...),
    ExistingSplitId(...),
    InternalError(...),
}

/// A split manifest carries all meta data about a split
/// and its files.
struct SplitManifest {
    /// the index it belongs to or is destined to belong to.
    index_id: String,

    /// The set of information required to open the split,
    /// and possibly allocate the split.
    metadata: SplitMetaData,

    /// The list of files associated to the split.
    files: Vec<ManifestEntry>,
}

struct SplitMetaData {
    /// Split uri. In spirit, this uri should be self sufficient
    /// to identify a split.
    //  In reality, some information may be implicitly configure
    /// in the store uri resolver, such as the S3 region.
    split_uri: String

    /// Number of records (or document) in the split
    num_records: u64,

    /// Weight in bytes of the split
    size_in_bytes: u64,

    /// if a time field is available, the min / max timestamp in the segment.
    time_range: Option<Range<i64>>

    /// Number of merge this segment has been subjected to during its lifetime.
    generation: usize,
}
```

## Publish splits (W)

```rust
/// Records a split as published.
///
/// This API is typically used by an indexer who needs to publish a new split.
/// At this point, the split files are assumed to have already uploaded.
/// The metastore only updates the state of the split from staging to published.
///
/// It has two side effetcs:
/// - it makes the split visible to other clients via the ListSplit API.
/// - it guards eventual recovery procedure from removing the split files.
///
/// Unless specified otherwise in the implementation, the metastore DOES NOT
/// do any check on the presence, integrity or validity of the metadata of this split.
///
/// A split successfully published MUST eventually be visible to all clients.
/// Stronger consistency semantics should be documented in the implementation.
///
/// If the split is already published, this API call returns a success.
fn publish_split(split: SplitId) -> Result<(), PublishError>;

enum PublishError {
    DoesNotExist(SplitId),
    SplitIsNotStaged {
        split: SplitId,
        previous_state: State
    },
    InternalError(...)
}
```

## List splits (W)

```
/// Returns the list of published splits intersecting with the given time_range.
/// Regardless of the timerange filter, if a split has no timestamp it is always returned.
/// Splits are returned in any order.
fn list_splits(index: IndexId, state: State, time_range: Option<TimeRange>) -> Result<Vec<SplitMeta>, ListSplitsError>;
```
enum ListSplitsError {
    IndexDoesNotExist(IndexId),
    InternalError(...)
}

List splits is used:
- by searcher with state=Published, and often with some timestamp range.
- by recovery procedure with state=Staging, and state=ScheduledForDelete
- by eventual garbage collection procedure with state=ScheduledForDelete

## Delete split (W)

```
/// Marks a split as deleted.
/// This function is successful if a split was already marked as deleted.
fn mark_as_deleted(split_id: SplitId) -> Result<(), MarkAsDeletedError>;

enum MarkAsDeleteError {
    DoesNotExist(SplitId),
    InternalError(...)
}

///
/// This function only takes split that are in staging or in mark as deleted state.
fn delete_split(split_id: SplitId) -> Result<, DeleteSplitError>;

enum DeleteSplitError {
    DoesNotExist(...),
    Forbidden(...), // deleting a published split is forbidden
    InternalError(...)
}
```

# File-in-object-storage based implementation

We simply serialize all of the splits associated to a single index into one large file.
We do not enforce any lock, and having several concurrent writer can lead to corruption (similarly to several datalake meta store).

The file has the following format.

```json
{
    "index": {
        // Possible index metas
    },
    "splits": {
        <split_id_1>: {
            "metadata": <SplitMetaData>,
            "files": [<manifest_entries>],
        }
    }
}
```

**Comment by evanxg852000** [comment]
@fulmicoton on the last part regarding the lock. how do we want to avoid multiple IndexWriter from corrupting the meta-store file without locking? Are we just settling with one IndexWritter per Index?

**Comment by fulmicoton** [comment]
We don't do anything... Only one Indexwriter per index supported for S3 stuff

**Comment by mosuka** [comment]
@fulmicoton @guilload 
What is the `ManifestEntry` introduced in Stage splits code? Is there a detailed explanation or code sample somewhere?
And, what exactly do you mean by a split needs to be staged before uploading any of its files to the storage?

**Comment by fulmicoton** [comment]
Manifest Entry a struct that contains some information about each file metadata. They checksum, their size, their filepath if I recall correctly. You can have a look at the struct in barrel.

> what exactly do you mean by a split needs to be staged before uploading any of its files to the storage?

In tantivy and in Quickwit, we need to be tolerant with to failure, at least to the extent of the Fail-stop assumption.
As long as the memory is not corrupted... The system should still work as expected.

That means that if your kill your indexing CLI while it is running, you should not end up with a corrupted index.
You should not have dangling file on S3 either.

For this reason, before registering any files, we need to record somewhere our intent to upload files.
When we restart the CLI, the CLI will check which files are in the Staged state and remove them...

Another approach would be to list the files from the stoarge, and remove all of the files in the directory that are not useful to the index according to the index meta. We do not use this approach because  a user that added its own files to the directory could see their file deleted by Quickwit. Besides, listing files on S3 can rapidly get slow, and it would require to add an extra method to the Storage trait.

**Comment by mosuka** [comment]
@fulmicoton @guilload 
I have a question about `list_splits`.
Assume that there are splits that contain the following range in the meta store.
If I call the `list_splits` function with the following range, which splits should the return value contain?

split_1 : std::opts::Range { start : 0, end : 100 }, SplitState::Published
split_2 : std::opts::Range { start : 100, end : 200 }, SplitState::Published
split_3 : std::opts::Range { start : 50, end : 150 }, SplitState::Published

list_splits( SplitState::Published, std::opts::Range { start : 50, end : 200 } )

Is the above `list_splits` returns value expected to be `split_2` and `split_3`? or `only split_3` ?
Can you tell me the specification of the filter using `time_range` in `list_splits`?

**Comment by guilload** [comment]
We want to retrieve any split that overlaps with the time range. So for a `[50, 200)` range, every split that has `range.end >= 50` or `range.start < 200` is a candidate.
