### ISSUE TITLE
Implement warm_up for fastfield

### ISSUE THREAD

**Issue by evanxg852000** [quickwit-inc/quickwit#129]

**Comment by evanxg852000** [comment]
@fulmicoton  the name  `warm_up_fastfield`  suggests we are dealing with one fast field. are we only concerned about the timestamp field?
Currently, I am using all fast fields in the schema, so I am thinking something might be off with my understanding.

**Comment by fulmicoton** [comment]
ah yes plural would be better.
we don't want to load all fast fields though. Only those required for the query.

**Comment by evanxg852000** [comment]
So I think we can add a method to docMapper `DocMapper::fast_fields(request) -> Vec<Field>`

**Comment by fmassot** [comment]
from my understanding, the fast fields are used by the quickwit collector, so I would ask the quickwit collector to know which fast fields to load.

**Comment by fulmicoton** [comment]
@fmassot is correct. Think about the timestamp fields. It is useful if some filtering is happening. If there are no timefilter we don't need to load it.

**Comment by evanxg852000** [comment]
@fulmicoton So my question is not there by the way, currently the QuickwitCollector has the list of fast_fields as Vector of field and it is that one I am using to warmup. My question here is how do we intend to populate that list of fast_fields. since we cannot use all from the schema. To me the `request` parsing was the best place. Ideally `Query` could contains a similar thing like `query.query_terms(&mut terms);` to get a list of fast_fields related to the query. It's in that rabit hole I am trying to dig.

**Comment by fmassot** [comment]
Getting the list of fast fields out of the query is not sufficient as we need also the information about how to filter those values. 

I suggest to open another issue to discuss the way we can use the quickwit collector to filter out document based on range queries defined by the user.

**Comment by fmassot** [comment]
closed in #137
