### ISSUE TITLE
Better error message when trying to create an index at the bucket root.

### ISSUE THREAD

**Issue by fmassot** [quickwit-inc/quickwit#132]
The command and the generated error:
```
quickwit-cli new --index-uri 's3://quickwit-dev/test-wiki-cli' --doc-mapper-config-path examples/doc_mappers/wikipedia_doc_mapper.json
Command failed: Failed to open metastore: `MetastoreError(kind=InternalError, source=StorageError(kind=Io, source=Invalid uri: s3://quickwit-dev))`
```

The error "invalid uri" is very generic. We could fail immediately by saying that we need at least 3 "directories" for the index uri on S3.

**Comment by evanxg852000** [comment]
@fmassot  This will also affect both storages. That is `s3` and `file` do we want this behavior?

**Comment by fmassot** [comment]
@fulmicoton have updated error messaging in metastore so it's worth checking if the issue can be closed or not, I saw good parts in Paul's refactoring so I bet this is ok now :)

**Comment by fulmicoton** [comment]
The error message is probably pretty bad today indeed

**Comment by evanxg852000** [comment]
So this issue is still around after checking, just that the message is different now.
```
Command failed: Failed to open metastore: `Another error occured. `Failed to open storage hosting the single file metastore.`. Cause: `StorageError(kind=Io, source=Invalid uri: s3://quickwit-dev)
```
currently, FileStorage and S3 storage behave differently. 
- S3 can only work with a three part uri `s3://quickwit-dev/indexes/data`
- FileStorage can work from two parts `file://quickwit-dev/data`

**Comment by fmassot** [comment]
We can accept different behavior as long as this is expected. `s3://quickwit-dev` is indeed not a valid path for S3.

**Comment by fmassot** [comment]
By the way, for me the confusion we can have around this generally comes from the fact that we do not explicitely tell to the user that we have the concept of metastore behind.
