### ISSUE TITLE
Think of a solution to add integration tests

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#134]
Quickwit-cli have a bunch of commands that interacts with each other.

We need to make it very easy for developer to run a bunch of a scenario and check for non-regression.
Typically all of the scenario in README and tutorial should be part of our CI.

Right now we do not have anything that looks like a integration test like this.
We need to first discuss the right practical solution and then implement it.

**Comment by evanxg852000** [comment]
@fmassot  Currently we have these options:
- `tests/cli.rs` as described here https://rust-cli.github.io/book/tutorial/testing.html; this is also what's used in vector.dev
- There is also [lit](https://crates.io/crates/lit) crate inspired from LLVM.  I am not fan of having annotations for testing.

Also, there is the question of temporary folders and files. I think we should use `tempfile` crate for this. Any file we want to create will just be created right in the test with the content in the test code. It might lead us to larger code files, but we get everything as code.

**Comment by fmassot** [comment]
I think integration tests are pretty good thanks to @evanxg852000 PR. 

I think we will polish one or two more tests based on the doc tutorials so we can keep the issue open.

**Comment by fmassot** [comment]
CLI tests are based on Wikipedia and hdfs logs config used in the tutorials so we are good for now on this.
