### ISSUE TITLE
Add quickwit-cluster package

### ISSUE THREAD

**Issue by mosuka** [quickwit-inc/quickwit#141]
Add the `quickwit-cluster` package.
This package is used to build a cluster of search nodes.
The SWIM protocol is used to build the cluster, allowing quickwit to perform node discovery on its own.

- create a `quickwit-cluster` directory into `quickwit`. `quickwit-cluster` contains cluster component and cluster-service (gRPC component for cluster management).
- protobuf stuff goes in `quickwit-proto`. (At first, put everything in `quickwit-proto`, and separate if it is needed later).
- The search-service (gRPC component for search) will go into `quickwit-search` (If there is a problem, change to a different package).
- the starting of the node (the search-service and the cluster-service) happens in `quickwit serve` subcommand in `quickwit-cli`.

Related Issue: https://github.com/quickwit-inc/quickwit/issues/93

**Comment by mosuka** [comment]
Created a draft pull request.
https://github.com/quickwit-inc/quickwit/pull/143/files

**Comment by mosuka** [comment]
@fulmicoton 
I thought it would be better to put `search_service.rs` in `quickwit-cluster` as well as `cluster_service.rs`. This is because I think it is easier to understand the `quickwit-cluster` package as a package that contains the server implementation of quickwit.
How about renaming the `quickwit-cluster` package to `quickwit-server`?

Since the following `Cluster` is actually a server implementation with cluster functionality using `ArtilleryCluster`, we would like to rename it from `Cluster` to `Server`.
https://github.com/quickwit-inc/quickwit/blob/1877bd12a4709341d22cb8692100d9a19f0a91ef/quickwit-cluster/src/cluster.rs#L76

What do you think?

**Comment by fulmicoton** [comment]
Can you rebase? We do have quickwit-serve that is in charge of starting the services.

The idea would be to start the search service, the cluster service and the rest API in that project.
Quickwit cluster would just implement the cluster service.

We can also move the search pool into quickwit-search or quickwit-serve. That way quickwit-cluster will be only be doing cluster formation.

**Comment by mosuka** [comment]
Thank you for your feedback. I'll change the branch.
