### ISSUE TITLE
Add telemetry

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#142]
We want to gather some information about our user's usage to help us drive the development  of the product.

It should be possible to disable telemetry via an environment variable.
Telemetry failure should be "swallowed" and "ignored".

The telemetry should contain the following information
- an scrambled host specific identifier
- event information or errors

**Comment by evanxg852000** [comment]
@fulmicoton  Do currently have any tool/library (ex. open telemetry) in mind or is this open for discussion?

**Comment by fulmicoton** [comment]
@evanxg852000 no tools. We are actually still discussing whether this is a good idea or not.

**Comment by fmassot** [comment]
could be interesting to log which backend is used S3 or file.
