### ISSUE TITLE
Implement a DocMapper for test

### ISSUE THREAD

**Issue by evanxg852000** [quickwit-inc/quickwit#145]
We need to test a few logics including `extract_fast_field_names` that depend on DocMapper implementation.
Find a way to mock or implement DocMapper for test and use it.
[This Commit](https://github.com/quickwit-inc/quickwit/commit/55ab8a36047e027ed9c552618b7b594ab9b94779) illustrates the issue

**Comment by fmassot** [comment]
Actually I think we're ok right now on that subject. I'm closing it. Feel free to repoen it if needed.
