### ISSUE TITLE
Remove field resolving from the doc mapper

### ISSUE THREAD

**Issue by fmassot** [quickwit-inc/quickwit#152]
We should only do some validation on fields but no resolving.

**Comment by evanxg852000** [comment]
@fmassot  I think this means replacing all references to `Field` in the DocMapper with `String` denoting the name. right?

**Comment by fmassot** [comment]
@evanxg852000 indeed, but we need to keep validation stuff, as long as resolving remains inside the doc mapper, this is ok.

**Comment by fmassot** [comment]
closed by #153
