### ISSUE TITLE
Remove doc mapper type from CLI

### ISSUE THREAD

**Issue by fmassot** [quickwit-inc/quickwit#157]
Currently, we should expose only the default doc mapper as the two others are either too restrictive for wikipedia or not really  useful for the flatten doc mapper. Indeed the flatten one would be useful with a flatten data type like the one implemented in barrel but it's not available in quickwit. 

Or maybe I don't see some use cases with the flatten one where we store the json in only one string field.

**Comment by fulmicoton** [comment]
agreed!
