### ISSUE TITLE
CLI small fixes

### ISSUE THREAD

**Issue by fmassot** [quickwit-inc/quickwit#158]
need to fix:
- name "Location of the metastore-uri" => location of index-uri
- name of command options from peer_seeds to peer-seeds

**Comment by evanxg852000** [comment]
I think the first one should be `Locations of the target indexes`

**Comment by evanxg852000** [comment]
@mosuka  may have already taken care of this in the Distributed search PR.

**Comment by mosuka** [comment]
@evanxg852000 
Thank you for letting me know. I’ll take care of this.

**Comment by fmassot** [comment]
this was done in #141
