### ISSUE TITLE
Inconsistent rest search request with command line usage

### ISSUE THREAD

**Issue by fmassot** [quickwit-inc/quickwit#162]
When creating, indexing and serving, we always refer to an index by its URI.

But for querying on the rest API, we need to pass the `index id` as a path param like this ``.

This is not really consistent. We can either:
- put the index uri in the query and not use the index id 
- be more explicit in the documentation of what we are doing with an index uri: metastore uri + index id

I vote for the second.

**Comment by fulmicoton** [comment]
I vote for the second too.

**Comment by fmassot** [comment]
done in #263
