### ISSUE TITLE
Add a File system storage

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#20]
This is only relevant after the merge of #18.

We should handle "file://" as a valid protocol and allow people to store and consume files on their local file system.

- [ ] add a file Storage
- [ ] add a file StorageFactory
- [ ] add it to the default StorageUriResolver
- [ ] test

**Comment by evanxg852000** [comment]
Just noticed this after my comment on https://github.com/quickwit-inc/quickwit/issues/2#issuecomment-842190353 will take it up
