### ISSUE TITLE
Add datasets used in tutorial in quickwit public aws bucket 

### ISSUE THREAD

**Issue by fmassot** [quickwit-inc/quickwit#201]
- [x] hdfs log:
- [x] wikipedia short (10000 first logs) and long version 
- [ ] commoncrawl ?
- [ ] github archive ?

**Comment by fmassot** [comment]
@PSeitz this is the dataset I used for hdfs.

**Comment by PSeitz** [comment]
I get access denied for that link
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>5KH7XCCVAVJ6R739</RequestId>
<HostId>
esil5wceQKrvg4bS45+EuVoFW0ZXpo/D3eOnKbrrQUGr7TDKZKKeFLtdsJB3vUtTMhFyGe5Ovf8=
</HostId>
</Error>
```

**Comment by fmassot** [comment]
arf, sorry, I thought it was public automatically, it is public now.

**Comment by fmassot** [comment]
the first two are enough for the release 0.1.

**Comment by fmassot** [comment]
Closing the issue as we are good for now, common crawl and github archive will require some additional work to process the data and should be treated in specific issues.
