### ISSUE TITLE
Faster CI

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#202]
We should make our CI faster.

There are two things that can be improved:
1) `cargo install` of non trivial stuff (deny, tarpaulin, ...). action-rs supposedly build, signs and caches those, but the caching seems broken these days. Also we should inspect the risk of supply chain attack. I did not understadn if action-rs was maintained by github or not.
2) compiling external crates over and over. It would be nice to cache that
3)  compiling our subcrates even when they are unchanged.

There are different ways to fix this, but one low hanging fruit could be to use our own builder Docker image with all of the tooling pre-installed. 
With a bit of imagination and trickery it can partially address 2) as well.

Finally supposedly github handles build_kit which is the solution Adrien set up of us locally in barrel. It might be difficult to set up however.

**Comment by fmassot** [comment]
yes this is really annoying as we are all pushing some code.... I may not wait for the release to optimize that...
