### ISSUE TITLE
doc mapping naming could be better

### ISSUE THREAD

**Issue by PSeitz** [quickwit-inc/quickwit#209]
When creating an index a doc mapping is required, but doc mapping may not be an ideal name, since mapping is just one aspect of the config. There are other options like the fields and their types. 

index config could be a better name, which could then cover other aspects like merge policy and retention policy

**Comment by fulmicoton** [comment]
that makes sense.
What do you think @fmassot ?

**Comment by fmassot** [comment]
We discussed that on slack and indeed I expected to change that name sooner or later...  and `index-config` is right I think.

This is especially true when creating an index using the CLI, passing the arg `index-config` is much better as everybody understands clearly what it is about. 

But I was little bit scared of changing the name in the code. So we need to check that part too.

**Comment by fmassot** [comment]
```rust
pub struct IndexMetadata {
    pub index_id: String,
    pub index_uri: String,
    pub config: Box<dyn IndexConfig>,
}

pub trait IndexConfig: Send + Sync + Debug + DynClone + 'static {
    fn doc_from_json(&self, doc_json: &str) -> Result<Document, DocParsingError>;
    fn schema(&self) -> Schema;
    fn query(&self, request: &SearchRequest) -> Result<Box<dyn Query>, QueryParserError>;
    fn default_sort_by(&self) -> SortBy {}
}
```

**Comment by fmassot** [comment]
Actually the semantic seems ok
