### ISSUE TITLE
Add cargo deny check in the CI

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#21]
Cargo-deny makes it possible to check for license inconsistency.

We should add it to our CI.
https://crates.io/crates/cargo-deny

**Comment by guilload** [comment]
If I understood correctly, you want to use `cargo-deny` on our own repo to ensure that we have set up our license correctly in the various packages that we will publish?

**Comment by fulmicoton** [comment]
Sorry for the confusion.

No I meant that our commercial license makes it so that we cannot depend on
a dependency with a copyleft license.

Le jeu. 13 mai 2021 à 07:18, Adrien Guillo ***@***.***> a
écrit :

**Comment by guilload** [comment]
Makes sense, the word inconsistency got me ;)
