### ISSUE TITLE
Support directory & remote dataset

### ISSUE THREAD

**Issue by evanxg852000** [quickwit-inc/quickwit#223]
The initial requirement for indexing was to support:
- Directory traversal to read documents for indexing.
- Allow fetching document from a remote source

This needs to be discussed of and implemented.

**Comment by fmassot** [comment]
I suggest to either close this issue or specify more clearly what you had in mind. For remote sources, I think we are starting handling it with kafka. For directory traversal, it is indeed interesting as we may want to index all files in a S3 bucket. If you want to keep it here, please create a dedicated issue on it.
