### ISSUE TITLE
IndexConfig everywhere

### ISSUE THREAD

**Issue by fmassot** [quickwit-inc/quickwit#228]
@PSeitz starts renaming doc mapper to index config but there are many file & dir names still out there with doc mapper

**Comment by fulmicoton** [comment]
I am mostly concerned by the names in the CLI.

**Comment by fmassot** [comment]
I'm taking this issue

**Comment by fmassot** [comment]
I notably fixed the CLI wording in #232, the renaming of project / directories is not required for the release.

**Comment by PSeitz** [comment]
everything should be renamed now, I think
