### ISSUE TITLE
Write documentation for Quickwit CLI

### ISSUE THREAD

**Issue by guilload** [quickwit-inc/quickwit#24]
The documentation should include the following section:
- [x] a "Getting Started" section providing a quick overview of what the CLI can do
- [ ] a "Commands" section describing each command in detail
- [ ] a guide or tutorial explaining how to index and query a dataset from start to finish

**Comment by djKooks** [comment]
Seems interesting project 👍 
So is this project targeting search engine, with storage?

**Comment by fmassot** [comment]
hi @djKooks, thanks! [tantivy](https://github.com/tantivy-search/tantivy) (search and storage included) is the core and we are building on top of it a distributed search with a rest api + storage on object storage (S3 for example) or any storage that enables range queries. 
Don't hesitate to come on tantivy gitter if you are interested or if you want to discuss you use cases!
