### ISSUE TITLE
Error message in the installer

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#276]
I am getting the following error when running the installer.
 
--------------------------------------------------------------------------------

```
                                   Q U I C K W I T
                                      Installer

--------------------------------------------------------------------------------
Website: https://quickwit.io/
Docs: https://quickwit.io/docs/
--------------------------------------------------------------------------------

sh: 252: [[: not found
sh: 259: [[: not found
>>> Unknown architecture from ldd: ldd (Ubuntu GLIBC 2.33-0ubuntu5) 2.33
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
>>> Downloading Quickwit via https://github.com/quickwit-inc/quickwit/releases/download/v0.1.1/quickwit-v0.1.1-x86_64-unknown-linux-gnu.tar.gz
>>> Unpacking archive ...

>>> Install succeeded!
>>> To start using Quickwit:

    ./quickwit --version 

>>> More information at https://quickwit.io/docs/



```

**Comment by fulmicoton** [comment]
There are two bugs in there.

The sh: 252 seems fixed in the installer script on github. It signals a bash idiom executed in sh.

The unknown architecture from ldd is something that reproduces even with the version on github.

I suggest we stop trying to be smart with libc and just ship binaries with musl?

(I just asked twitter https://twitter.com/fulmicoton/status/1414389034080608257)

**Comment by fmassot** [comment]
does this install totally fails? did you try running the binary?

**Comment by fmassot** [comment]
concerning musl, I really don't know, vector put a warning on that here https://vector.dev/docs/setup/installation/#using-static-musl-builds

**Comment by fulmicoton** [comment]
@fmassot no the binary was correctly downloaded.

**Comment by evanxg852000** [comment]
I am looking into this
