### ISSUE TITLE
Garbage collect only old (enough) splits

### ISSUE THREAD

**Issue by evanxg852000** [quickwit-inc/quickwit#320]
The garbage collection should only consider removing old enough stale split, otherwise, it could be removing splits that are being uploaded by another process.

**Comment by guilload** [comment]
I suggest having some sort of `grace_period` parameter with a sane default in the API so that users who know what they are doing can "gc" over a shorter or longer period of time.

**Comment by evanxg852000** [comment]
If I understand correctly we want to have a flag `--grace-period` that specifies the age to leave not old enough stale split alone.
What unit do we want? minutes, hours, seconds or a mix of all?

**Comment by fmassot** [comment]
I will support the 3, something like a number + a letter: `10m` for ten minutes.
