### ISSUE TITLE
Add CSV/RowBinary output format to Search API 

### ISSUE THREAD

**Issue by fmassot** [quickwit-inc/quickwit#324]
**Is your feature request related to a problem? Please describe.**
We want Quickwit to be easily integrated into row-based engines like SQL databases.  

**Describe the solution you'd like**
Exposing a CSV and a row binary format that a user can choose with a query param `format` would be sufficient. 

CSV format: https://datatracker.ietf.org/doc/html/rfc4180
RowBinary format: to define.

**Comment by guilload** [comment]
`format` is too generic and confusing in my opinion. `output-format`?

**Comment by fulmicoton** [comment]
What is a bit tricky is that the data is not tabular.
Would we then just returns the hits?

If the goal is to emit a list of keys extracted from a given fastfields, I'm not sure where to put that in the API.
It could be a different endpoint for instance.... But it is definitely not just a format.

**Comment by fmassot** [comment]
Indeed. 

Currently we have this endpoint with query params such as `startTimeStamp`, `startOffset `, `maxHits`:
`api/v1/indexes/<index name>/search`

If we look at what elastic [offers](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-fields.html#docvalue-fields), we can see that they let the user defines a list of `fields`, `runtime fields` and `docvalues fields`, they even let the user extract values from the source field.  This is interesting but overkill for us.
Moreover, I feel that mixing all in one endpoints can be confusing and we can maybe define a dedicated one to retrieve hits only. 
Like this `api/v1/indexes/<index name>/search/hits` where you can define these new parameters:
- `fastField` (required) to define a list of fast fields to extract
- `outputFormat` with values in [`csv`, `rowBinary`]

In the future, we can add a `field` parameter to specify which field to extract.

**Comment by PSeitz** [comment]
`fields` can be really important for some use cases, e.g. large corpus documents where you are just interested in the ids.

About the csv etc. support I think it's better to have a external transformer, which takes the json result and emits something else. This transformer should be quite easy to build, when you know your data model and wouldn't necessarily be on our side.

**Comment by fmassot** [comment]
This endpoint should be very performant for use cases like fetching millions of some given field values. 
Using fast fields is a must have in this case. Concerning the output format, I would not want to have an intermediate format such as json.

**Comment by PSeitz** [comment]
So to use the Search API as data-extraction? The typical search returns top n results and some aggregations

**Comment by fmassot** [comment]
As discussed earlier, we can start with a very simple API with the following properties:
- support only one fast field in query parameters
- support csv format

**Comment by fmassot** [comment]
@evanxg852000 the idea is to implement a collector that collects fast field values.

**Comment by evanxg852000** [comment]
I still have a couple of questions:
- DynamicFastfieldReader is generic, make it not object safe for things like Vec<DynamicFastFieldReader> 
-  Also `FastValue` is said to have an underlying value of u64 
from the above Is it ok to wrap it into something like ? that is  using u64 as generic value to read all FastFields
```rust 
enum GenericFastFieldReader {
    U64(DynamicFastFieldReader<u64>),
    U64s(MultiValuedFastFieldReader<u64>),
}
```

The intent is to have endpoint param `fastField` to accept `Vec<String>` just search_field

Regarding single/multi-valued fast field, I think using a `Vec<FastValue>` in both cases should be fine.

In order to output to the row format, we can apply a cartesian product of the FastField values to the merged result while also retaining the current search params for pagination as this might get out of hand quickly for converting it into a row based output.
for example the hit bellow:
```json
[ 
  {
    "doc_id": 10,
    "fast_1": [1,2],
    "fast_2": [3,4]
  }
]
```
becomes

| id   | fast_1 |  fast_2 |
|------|----------|----------|
| 10 |  1  | 3  |
| 10 |  1 |   4 |
| 10 | 2 |    3 |
| 10 | 2 |    4 |

@fmassot  you probably have thought about all this and know already why this might not work for this use case but I want to know your opinion.

**Comment by fmassot** [comment]
I would start with a very very simple implementation:
- forget about the multi-valued fast field
- take only one fast field in the input

Using `u64` does not work for bytes fast field. 

As start, we could only support all fast field types except bytes fast field and send. a `u64` to the root node. 

We could have:

```rust

pub struct PartialHit {
    pub sorting_field_value: u64,
    pub split_id: ::prost::alloc::string::String,
    pub segment_ord: u32,
    pub doc_id: u32,
    pub fast_field_value: u64
}

```

If we authorize the user to ask for several fast fields, we can have a `Vec<u64>` in place of the `u64`.
Here we take advantage of having u64 values for all fastfields. But let's forget that for the moment.

On the root node, we need to convert u64 to the right data type according to the schema and return binaries.

So here we have an oversimplified approach, let's call it *Solution 1*.


*Solution 2*
Instead of having a `PartialHit` with only a `u64` field for fast field value, we can use some struct like the tantivy enum `Value` and serialize/deserialize it to have the right value. 

*Solution 3*
`PartialHit` can directly have `fast_field_value: bytes`. Cool for the rowbinary format?

I'm stopping here because it's too late. To be completed.

**Comment by fmassot** [comment]
Concerning the name of the endpoint, what do you think of `search/stream` ?

**Comment by PSeitz** [comment]
> Concerning the name of the endpoint, what do you think of `search/stream` ?

I would call it stream, if there was some streaming logic behind it that differs from the normal search.

api/v1/indexes/<index name>/data-extraction ?

**Comment by evanxg852000** [comment]
I think we will figure this out naturally when we have a working shell.

**Comment by fmassot** [comment]
Let's summarize our previous discussion: we need to be focus on performance and we can forget using `PartialHit`.

The new plan is:
- having an endpoint called `search/stream` (we really want to stream the result) that takes additional parameters `fastField` and `outputFormat`
-  the root node will send requests with these parameters so that leaves return directly the data in the right format and the sufficient data.
- the root node will concatenate bytes leaves results and return it 
- a leaf node will stream results by split

**Comment by evanxg852000** [comment]
Sorry @fmassot just reading your comment but I guess these are things I can already change in the PR  easily as long as the main logic is correct.
