### ISSUE TITLE
Sometimes the unit test of a multi-node cluster fails.

### ISSUE THREAD

**Issue by mosuka** [quickwit-inc/quickwit#333]
**Describe the bug**
Running the following tests may fail in rare cases.
The error message may change from time to time and maybe it's a race condition.

```
cargo test -- --nocapture  test_cluster_multiple_node
```

```
test cluster::tests::test_cluster_single_node ... ok
test cluster::tests::test_cluster_multiple_node ... FAILED
failures:
---- cluster::tests::test_cluster_multiple_node stdout ----
[127.0.0.1:33529, 127.0.0.1:34539, 127.0.0.1:42945]
[127.0.0.1:33529, 127.0.0.1:34539, 127.0.0.1:42945]
thread 'cluster::tests::test_cluster_multiple_node' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /home/pascal/.cargo/registry/src/github.com-1ecc6299db9ec823/artillery-core-0.1.2/s
rc/epidemic/cluster.rs:90:19
failures:
    cluster::tests::test_cluster_multiple_node
test result: FAILED. 4 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 6.01s
```

```
running 1 test
[127.0.0.1:40155, 127.0.0.1:40451, 127.0.0.1:46737]
[127.0.0.1:40155, 127.0.0.1:40451, 127.0.0.1:46737]
thread 'bastion-blocking-driver' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', /home/pascal/.cargo/registry/src/github.com-1ecc6299db9ec823/artillery-core-0.1.2/src/epidemic/
state.rs:444:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test cluster::tests::test_cluster_multiple_node ... ok
```

**Comment by fulmicoton** [comment]
@mosuka can you investigate? it is probably a minor race condition.

**Comment by mosuka** [comment]
@fulmicoton 
Yes, I’ll investigate it.

**Comment by mosuka** [comment]
@fulmicoton @PSeitz 
The cluster is leaving the cluster consecutively, and I think that it is failing to send messages in artillery-core. (When tried to send a message that a member of the cluster has left the cluster, it is likely that the member to whom the message is sent is also no longer in the cluster.)

https://github.com/quickwit-inc/quickwit/blob/4d6d4bcd4a30d95578071c352d9728c73bc3ee16/quickwit-cluster/src/cluster.rs#L390-L392

As a temporary fix, I'm going to make it so that after the member left the cluster, the message waits for a small amount of time before it is sent and received, what do you think?

```
        cluster1.leave();
        // Wait for leaving the cluster.
        thread::sleep(time::Duration::from_secs(1));
        cluster2.leave();
        // Wait for leaving the cluster.
        thread::sleep(time::Duration::from_secs(1));
        cluster3.leave();
```

However, if we have a large cluster in production, it may happen that multiple nodes go down at the same time. We may need to modify the artillery-core side to avoid panic.

https://github.com/bastion-rs/artillery/blob/f526f980157b53dd236bde502205d6c5b5a23ce3/artillery-core/src/epidemic/cluster.rs#L90

https://github.com/bastion-rs/artillery/blob/f526f980157b53dd236bde502205d6c5b5a23ce3/artillery-core/src/epidemic/state.rs#L442-L444

**Comment by PSeitz** [comment]
I guess the best way would be to log an error or ignore instead of unwrap?

**Comment by mosuka** [comment]
@PSeitz Yes, I'll send a PR to the Artillery project.
