### ISSUE TITLE
Have quickwit serve serve multiple indices

### ISSUE THREAD

**Issue by jabis** [quickwit-inc/quickwit#345]
**Is your feature request related to a problem? Please describe.**
200 indexes would mean 600 ports for the rest api's

**Describe the solution you'd like**
I 'd rather have the index /api/v1/`indexname` to be dynamic - current workaround is executing shell which comes at a cost, where it'd be probably trivial to pass an array of configs to be served

**Describe alternatives you've considered**
running a shell.exec is costly with ever increasing indexes

**Additional context**
The rest servers do their job efficiently - they're just too rigid currently

**Comment by guilload** [comment]
Hi @jabis,

The `serve` command supports multiple indexes. You can pass a list of index URIs:
```
quickwit serve --index-uri s3://bucket/foo,s3://bucket.bar
```

The parameter name is misleading and should be called `index-uris`. Our docs should provide an example of such usage. We'll fix that.

**Comment by jabis** [comment]
Hi @guilload, 
Thanks for the prompt reply, and that's great, makes it easier to compare your solution with the existing stack for sure!
I didn't have a look at the source yet, just started to play around with the binary, and couldn't surmise this from the existing docs.

PS. Great work so far, love the premise of the project!

**Comment by fmassot** [comment]
Thanks for your kind words @jabis :)

Currently the serve command is not very practical to serve something with 100 indexes and the plan is just to give let the user define a metastore uri that host all the indexes.

> The parameter name is misleading and should be called `index-uris`. Our docs should provide an example of such usage. We'll fix that.

I'm not fond of adding `s`, as of now we use singular even for multi-valued fields (peer-seed or other fields in query params or elsewhere).

**Comment by fmassot** [comment]
I will close the issue for now then.

**Comment by guilload** [comment]
> I'm not fond of adding `s`, as of now we use singular even for multi-valued fields (peer-seed or other fields in query params or elsewhere).

I think that's also wrong and should be fixed too :)
