### ISSUE TITLE
Use Pascal's measure_time in quickwit

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#368]
Pascal made a tool to measure the time taken by long running functions and log the result. we could use it in our handlers
We could use that

https://github.com/PSeitz/rust_measure_time

or roll out our own tool. It might be nice to include this timing details in the response.
The payload in the demo was extremely helpful for identifying very tricky botllenecks. 

Please discuss solutions in this ticket.

**Comment by evanxg852000** [comment]
https://github.com/PSeitz/rust_measure_time

**Comment by evanxg852000** [comment]
Given how open this was, I spend time looking at distributed tracing and more specifically Jeager. Which happens to be also implemented by @fmassot. I think a distributed tracing mechanism will be more robust for us in the long run than a custom solution.

**Comment by fmassot** [comment]
closed with #446
