### ISSUE TITLE
Avoid sorting hits twice in search

### ISSUE THREAD

**Issue by fmassot** [quickwit-inc/quickwit#382]
Currently, we are doing the hits sorting twice.

Once when sorting `partial_hits` in `merge_fruits` step (inside, it's `top_k_partial_hits` is called)
```rust
let leaf_search_result = spawn_blocking(move || collector.merge_fruits(leaf_search_results))
```

Once when sorting `hits` after docs are returned
```rust
hits.sort_by(|hit1, hit2| {
        let value1 = if let Some(partial_hit) = &hit1.partial_hit {
            partial_hit.sorting_field_value
        } else {
            0
        };
        let value2 = if let Some(partial_hit) = &hit2.partial_hit {
            partial_hit.sorting_field_value
        } else {
            0
        };
        // Sort by descending order.
        value2.cmp(&value1)
    });
```

**Comment by fulmicoton** [comment]
It is fine as it is...

The second sort usually contains 20 documents.
In most case it is not worth doing anything smart.

**Comment by evanxg852000** [comment]
Yep, I agree with @fulmicoton  after analysis of this. We cannot get rid of the first sort. 
And because we want to optimize fetch document by split, the result gets out of order.
We could merge using Heap but that is still sorting

**Comment by fmassot** [comment]
Yes. So won't fix.
