### ISSUE TITLE
Gc test failing

### ISSUE THREAD

**Issue by evanxg852000** [quickwit-inc/quickwit#384]
The test `test_cmd_garbage_collect_spares_files_within_grace_period` is failing, caused by the way we currently [guess region from ec2 instance](https://github.com/quickwit-inc/quickwit/pull/379)

For environments where there is not AWS config, this returns quickly, but for environments where `AWS` is found, this takes a bit of time to complete. This also slows down the tests.

`test_cmd_garbage_collect_spares_files_within_grace_period` is failing because it relies on timer. we could adjust the grace period but I think a better approach is to guess the region lazily.

**Comment by fmassot** [comment]
I did not anticipate this bug. We can do 2 things: deactivate guessing from ec2 instance in tests env, or set `AWS_REGION` env variable to default value `us-east-1` to avoid using guessing from ec2 instance meta.
