### ISSUE TITLE
Implement a cache on the upload side.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#400]
Right now, the indexing pipeline simply uploads split ones they are ready.

Because we want to maintain a low time to search, we are producing relatively small splits that will be merge rapidly.
It would be beneficial to maintain a cache with the recently uploaded files, in order to avoid hitting at least on the first 2 merges.

This cache might contain relatively large files , and should be on SSD.
I think LRU is ok.

Losing data is absolutely ok (it is a cache), however returning truncated files or leaking files is not ok.
Ideally the cache should be resilient to restarting the indexing pipeline.

-- 

_Added information:_

We only cache entire files.

You won't be able to use the StorageWithCache trait unfortunately so that means creating your own wrapper.
We can call it, StorageWithUploadCache.

It needs to work for the following workload.

The cache entirely ignores slices. The wrapper directly calls the underlying storage. It also ignore get_all.
copy_to_file is on the hand trying to hit the cache.
When it is called, if the file is not in cache, just bypass the cache entirely. In other words, do not try to store the file into the cache.
The cache is populated upon put calls and when we restart the process. For a same path, any reasonable behavior is acceptable for the put. We don't want a bug, but you can assume our workload does not put the same file twice, so for instance no need to try to optimize and debounce those calls etc.
That way, you can entirely dismiss the problem of "what do I do if two call to get are performed?", how do I debounce them?
---

Added Info: Suggested design

Use a directory for the cache
We consider all of the file in that directory as our responsability. If the 
user saves stuff in it, it is their mistake.
For extra safety we can append `quickwit-cache/` to the directory that was given by the user.
We do not save any cache state file.

(One possible refinement:  we could have a limit of file size, above which the cache ignore the files)

Use a qualified `LocalFileStorage` as the cache (as opposed to `Box<dyn Storage>`)  
Add a move function to LocalFileStorage.

# Upon put.

If path ends with _temporary, bypass the cache.
Do not have cache freeing logic. If there isn't enough capacity, log a warning and do not cache.
The cache will get freed naturally via GC deletes. 
copy to <SPLITPATH>_temporary
upon copy success, move <SPLITPATH>_temporary to <SPLITPATH>
we save the file in a in memory (split_filename -> split size) hashmap.

# Upon get.

If path ends with _temporary, bypass the cache and hit the remote storage directly.
Check if the file exists in the in-mem hashmap, if it isn't hit the remote storage,
otherwise hit the cache.
If the fetching the file form the FS fails, then hit remote directly and log an error.
(no need to remove it from the hashmap - the capacity is still held -)

# Upon delete. (emitted by GC)

Remove from remote.
If it is in the hashmap, remove the file from the local cache, and remove from the hashmap.
If removing from the local cache fails, log an error.

# Upon opening an existing cache.

Run ls over the directory.
Remove all (or attempt to) all of the *_temporary files.
Add the valid split files in an in-memory hashmap (split_filename -> split size)?.

===================================================

The two normal patterns of usage for a given file will be
- PUT
- GET
- DELETE (but it is ok to remove it from the cache earlier)
(we get exactly once)

OR for a split that is larged enough to be considered matured (has been through enough
merge operation)
- PUT
- DELETE (but it is ok to remove it from the cache earlier)

**Comment by evanxg852000** [comment]
@guilload  Thinking about your proposed solution, I think this implies anytime a `put` or `get` operation is performed we will need to get/set file metadata to make sure the file on disk `atime`, `ctime` is changed. I feel like potentially running through those files to get metadata and decide wich to evict could be lot of io compared to storing. 

Since we are expecting a large file to be managed by the cache. though a get operation returns quickly, The underlying file could be needed for a longer period. I am proposing using Guard Patterns, and using a variable `pin_count` to count how many guards exist at a particular time while not allowing eviction of items with `pin_count` greater than 0. 

@guilload  @fmassot Please can you look and give early feedback. 
I still need to add persistence, proper error handling, and tests
https://github.com/quickwit-inc/quickwit/commit/e198a0b1f02d8d6e798d20a7ca1c0537d29a9cfb

**Comment by guilload** [comment]
Let me confirm but I believe that as long as a process holds a file descriptor on a file, the OS will wait for the process to release the file before honoring any delete request. With that assumption in mind, I think we can aim for a much simpler solution that periodically checks the `atime` of the watched files and deletes those that haven't been accessed for a given threshold.

**Comment by evanxg852000** [comment]
I will investigate and test that route.  As you pointed out even if I make `item.value` private and I impl Deref as my initial plan. one can still open the file using the guard (OK) but he can still pass the FD to a function while the guard is dropped. 
So for this to work we will have to force the FD as part of the V stored in the cache and this brings too many rules for just caching interface.

**Comment by guilload** [comment]
Here is a simple solution @evanxg852000 and I designed for this first pass:

1. On `put`, if the payload is in memory, copy the payload to disk, at `{root}/{split_id}` or move the file to  `{root}/{split_id}`. Upload the file to `{split_uri}` with the appropriate storage.
2. On `get`, download the file if it is not already on disk and then serve slices from disk.
3. Periodically traverse `{root}` and delete files that have not been accessed recently based on `atime`.

This approach seems fine as long as `{root}` does not contain too many files (no more than a few hundred?). We also assume that a `split_id` is unique across all indexes so we can map a `{split_uri}` to `{root}/{split_id}`.

 There are a few gotchas for implementing this:
- ensure `Storage::copy_to_file` is atomic;
- ensure that while a file is being downloaded, a second request for the same file does not trigger a second upload.
  
@fulmicoton, we'd like your opinion on this.

**Comment by fulmicoton** [comment]
Unfortunately, I don't think we can rely on atime. The default setting in the kernel is relatime, which means that as long as the file is not modified, atime will be updated only once in a while (once a day by default).
https://blog.confirm.ch/mount-options-atime-vs-relatime/

We could "touch" files in order to force update the modified time, but it feels very wrong for many reasons.

Therefore, we should keep the list of files in a RAM datastructure, use a LRUCache with a size capacity and a number of object capacity (say we save maximum 1000 files).
We can save this metadata atomically upon every single read. Saving a file atomically is not super easy but we can copy what is done in tantivy. Note that we need to make sure that the intermediary tempfile is on the same filesystem to avoid crazy bugs.

The meta file is read only upon start. For the first implementation, we can write the metafile upon every single read. In the future, we can write asynchronously once every 10 minutes if there is a change.

The idea of string all splits in the same directory sounds like a good idea. The splitid are indeed universally unique and we want to keep it that way. We can also prefix them with a hash of the storage uri if necessary.

**Comment by fulmicoton** [comment]
For our use case (a cache for the indexing side), we could also actually use the creation time tbh. The files are meant to be accessed only once.
