### ISSUE TITLE
Specification for what we need to have in the IndexConfig

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#405]
We have new notions in IndexConfig.

Sources... (do we need  tenant)?

Define and implement what IndexConfig should look like.

**Comment by fmassot** [comment]
## Parameters related to indexing that need to be configured
The following features need some config parameters that we can add to `IndexConfig`:
- commit policy: timeout and max docs count
- source config: this is specific to a source type like kafka, file. 
- threads, heap size per indexer
- indexer count
- compaction policy: we need to make some merges with specific rules (like merging only splits with same tags) and demuxing tags from splits. **This needs to be defined and is not yet treated here.**
 


## Questions
- do we want to have multiple sources for one index? Handling checkpoints from different sources can add some complexity that we don't really want to handle right now.  

## Indexing config example

Note: `timeout` is in seconds.

```json
{
  "indexing": {
      "commit_policy": {
        "timeout": 60,
        "num_docs_threshhold": 100000 
      },
      "indexer_count": 3,
      "num_thread_per_indexer": 2,
      "heap_size_per_indexer": 1000,
      "source": {
        "type: "kafka",
       "...": "..."
      },
     "compaction_policy": {
     }
  }
}
```

## Source config
### File
```json
{
  "type": "kafka",
  "path": "/home/quickwit/my-file-to-index",
}
```

### Kafka
```json
{
  "type": "kafka",
  "topic": "quickwit",
  "bootstrap.servers": "localhost:9092"
}
```
