### ISSUE TITLE
Tag split during indexing

### ISSUE THREAD

**Issue by evanxg852000** [quickwit-inc/quickwit#421]
Discuss and implement how tags are collected and added to splits during indexing.

**Comment by evanxg852000** [comment]
@fulmicoton @guilload I am thinking this should be handled as we do for the `timestamp` field. That is in the index config, we specify fields that should be used to collect the tags during indexing the same way we keep track of split time range.

```json
{
    "store_source": true,
    "default_search_fields": ["body", "severity_text"],
    "timestamp_field": "timestamp", 
    "tag_fields": ["device", "city", "tenant"],
    "field_mappings": [ ]
}
``` 

somewhere in the split  `update_metada` during indexing, we fetch the tag values and add to a HashSet of tags.
I think this way we don't even need to store it in the index.

**Comment by fulmicoton** [comment]
I am ok with the IndexConfig, but I think it might be easier to populate them in the packaging phase.
It will also be easier to recycle the function when we delete documents.

We would open the index, open the TermDictionary, and get the terms out of it.
