### ISSUE TITLE
Fix code coverage in CI

### ISSUE THREAD

**Issue by guilload** [quickwit-inc/quickwit#439]
**Describe the bug**
Code coverage [fails in CI](https://github.com/quickwit-inc/quickwit/runs/3387173610?check_suite_focus=true#step:10:490)

**Comment by PSeitz** [comment]
This is probably related to actors timing out

**Comment by PSeitz** [comment]
Reopening, issue still persists with 5 sec heartbeat

**Comment by fmassot** [comment]
Coverage is fine now. Closing.
