### ISSUE TITLE
Better supervisor

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#463]
Right now the pipeline supervisor retry logic has two problems.

First, it just retries right away. We should probably have some type of exponential backoff...
Maybe we should log a warning on the first issue, and an error on the second to help users configure pagers?
(@guilload what is the right practise here?)

Second (which is way more important)
Right now, if an error happens during the pipeline creation, we just fail.
This should also be part of the respawn process. 

The reason why it is deactivated is because, for the current CLI experience, we want to exit if there is a connectivity problem. There is a consensus however that this should be solved in #701.

**Comment by fmassot** [comment]
Now that we have connectivity checks and that we will validate params consistency before spawning, I wonder what kind of errors we can have here, here are some guesses:
- error when creating the local store, could be possible if we can't write into the cache directory
- metastore error when we retrieve the published splits, even though we checked before connectivity, the server may have network issues
- object storage errors coming from network issues (notice that there is already some retries on the storage layer)
- params errors coming from the fact that it may be hard to be sure at 100% that we have consistent parameters

To take a step back, we can think about the behavior we would want once we have the indexing server. On starting, the indexing server will spawn the supervisor and a quickwit user will monitor the status of this supervisor. If for some reason, the supervisor has exited, he will look at the logs and would want to restart once he fixes parameters inconsistencies, network issues.

As we lack some XP, I suggest to start with the basics, 3 retry and exponential backoff

```rust

let attempt_timeout = Duration::from_secs(5).min(timeout);
let backoff = ExponentialBackoff {
    max_interval: Duration::from_secs(5),
    max_elapsed_time: Some(timeout),
    ..Default::default()
};
```

copy-pasted from Kafka source :)

**Comment by fulmicoton** [comment]
@fmassot yes the "how do we deal with bad params" is solved by the connectivity check.

**Comment by fulmicoton** [comment]
I think we want a perpetual retry.

**Comment by guilload** [comment]
I don't know about the perpetual retry, at some point I'd like my process to return with an exit code > 0, especially for the `ingest` command.

**Comment by guilload** [comment]
Maybe perpetual retry for the service and bounded for the ad-hoc ingest?

**Comment by PSeitz** [comment]
If there's something constantly failing we should probably stop after some time and not continue forever?

Or can we expect that some issues disappear after some time.
