### ISSUE TITLE
Reenable failpoiint unit test on CI

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#472]
Failpoints tests seem to sometimes fail on CI and are running too long for comfort.
When it fails, the test runs normally for a bit and then seem stuck for 1hour+ without logging any error.

We need to investigate the issue. A first thing that can be done is raising the log level to info. (right now we only show error logs).

We also need to either
- make them run faster (by manipulating the scheduler?
- have them only run on PR merge ( not PR push) like we do for integration tests and coveralls. it could be part of coveralls.
That would mean introducing  a tarpaulin.toml configuration file to have several run with different features and arguments 
 https://github.com/xd009642/tarpaulin

**Comment by fmassot** [comment]
closed by #1026
