### ISSUE TITLE
Weird start times 

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#478]
Main is extremely slow on startup for any command. (e.g. quickwit serve, quickwit create)

The reason is unknown. Telemetry maybe!?

**Comment by fulmicoton** [comment]
It was already identified by @evanxg852000 in another message.
The problem is coming from the attempt to sniff the local region from the amazon endpoint.

We can limit the harm by using a singleton for the StorageUriResolver. One tricky problem is that we probably do not want to use this singleton in unit tests.

Also the metastoreuriresolver embeds a storage uri resolver.

**Comment by fmassot** [comment]
I would use another way. I would prefer postponing the guessing of the region that is coming too early. 
Typically, one day, we may authorize the user to put the region in the URI, the region will thus be set at the `S3CompatibleObjectStorage` level.
So I would put the region guessing at this level.

**Comment by fulmicoton** [comment]
Yes I think this is easier/better... And we can cache the result of this sniffing call.

I'd would still prefer to have a singleton though and remove the default implementation.
We keep adding caches in this, and I feel like making it easy to create your own StorageURIResolver will eventually hurt us.

**Comment by fmassot** [comment]
Ok.

But even with this singleton, I need to wait from 2 to 4 seconds for each command...

**Comment by fmassot** [comment]
We can keep the singleton but I suggest either removing the region guessing from ec2 instance or having an environment variable to activate it.
@guilload if you have better idea, this is welcomed.

**Comment by fulmicoton** [comment]
@fmassot what you suggested was a good idea... Or maybe I misunderstood you?
Can we make the call to local region lazily, only if an s3 uri is supplied?

**Comment by fulmicoton** [comment]
@fmassot I added a commit on top of your PR to make the s3 region lazy.

**Comment by fulmicoton** [comment]
ah sorry I'll try to be clearer next time. Your solution was better but I wanted to have both. What I suggested should have been another ticket because it is solving another problem.
