### ISSUE TITLE
minio support ?

### ISSUE THREAD

**Issue by gedw99** [quickwit-inc/quickwit#49]
current code looks very aws centric. What about minio support for those that dont want to be tied to a cloud provider ?

**Comment by fulmicoton** [comment]
We have already isolated the storage abstraction to this
https://github.com/quickwit-inc/quickwit/blob/main/quickwit-storage/src/storage.rs#L77-L100

Granted we only have a filesystem and an Amazon S3 implementation, but supporting other storage should be easy.
