### ISSUE TITLE
Schema constraint Schizophrenia

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#521]
`IndexConfig::tags_field` seem to suggest that not having tag field is possible, but we actually panic in the indexer if there are no tag field.

I am not sure what we should do:
- Make the tag field really optional
- Add the tag field automagically in the schema generated by the indexconfig.
- Document somewhere that not having a fast field is an error.
- panic in `IndexConfig::tags_field` if none.

**Comment by fmassot** [comment]
My 2 cents:

It's easier to think that the field `tags_field` is always in the schema and replace the `Option<Field>` by `Field` in `IndexConfig::tags_field`. This is a breaking change with 0.1 version but I think it's worth breaking it right now.

**Comment by fulmicoton** [comment]
I agree with that.
