### ISSUE TITLE
Rename records into docs everywhere?

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#534]
Heritage of barrel, we named our documents "records".

At that time, the goal was to make quickwit a search engine strongly dedicated to logs. 

Today, we still use the word record for doc in the splitmetadata.
I suggest we embrace our search DNA and call that a doc everywhere?

**Comment by fulmicoton** [comment]
@guilload your thoughts?

**Comment by guilload** [comment]
Yeah, `docs` all the way!

![5mmmhj](https://user-images.githubusercontent.com/3011588/132952220-fe8d1b37-dafc-479d-89f4-ba188516379b.jpg)

**Comment by fmassot** [comment]
Docs is better yes.
