### ISSUE TITLE
Consistent IndexUri vs IndexId

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#55]
# Index(Id/Url/Uri), Split(Id/Url/Uri)

Our doc and our code are inconsistent (independently and mutually) on these concept.

The goal of this document is to come up with a clear definition of what should be done.

The origin of the confusion is coming from the coexistence of 3 different product

- barrel
- quickwit version 1, as a CLI, where each command only apply to a single index
- quickwit in the future, which is seen as a better version of barrel.

Barrel is just a prototype and should only be here as a source of experience for the future... So let's exclude it from the discussion.

Going one step further, the source of the confusion is that the CLI only targets a single index. 
Our foundational abstraction however try to make us ready for the near future and try to address the problem of managing several indexes (duh 🙂).

The `serve` command could actually be a good candidate to already handle several indices, and can be a good pivot for the reflexion.

Here is the solution that I suggest:

- `metastore_url`: a self sufficient address to open a metastore. The MetastoreUrlResolver turns an url into a MetaStore object. The protocol helps choosing the right implementation. Examples:
    - s3://quickwit-indexes/
    - postgres://localhost/toto
- `index_id`: an id that only makes sense in the context of the meta store. The meta store is able to get a bunch of information about the index given an `index_id`. Most importantly, the `index_url` and a list of splits.
- `index_url` in the code: 
When we index, it serves as a base url to create the storage used to store splits. 
On search make it possible to resolve `split_relative_url` to a split_absolute_url.
- `split_id`: an url that points at the storage of a given split. We prefer to store a split_id and resolve things from the index_url for different reasons...  The most obvious one is that it makes it easier to move an index. For instance, if someone wanted to move an entire index from s3 to the local filesystem, it would only require copying all of the split files,  export a single file version of the metastore, and fix the index_url to the filesystem.
The less obvious reason is that we might want to create only one `Storage` object and fetech path including the split prefix path, rather than create one storage for every split.
- `index_url` in the CLI arguments : Here comes the cause of the ambiguity... Conceptually speaking, with the following setting, the create and the index cli (this is the same story for other cli) would look like
`quickwit create —meta-store-url s3://quickwit/ —index-id wikipedia —index-url s3://quickwit/wikipedia` 
`quickwit index —meta-store-url s3://quickwit/ —index-id wikipedia`. This is obviously not user friendly, error prone, and overkill in a world where we have only one index with a colocated metastore.
Rather than this, for quickwit v1, we only have one `index-url` argument. It is required to be a "storage url". We infer the meta-store-url and index-id from this index-url.
`quickwit index --index-url s3://quickwit/wikipedia`
- In `quickwit serve`, we also use the `quickwit serve —index-url  s3://quickwit/wikipedia` syntax, but we can also support the following 
`quickwit serve —meta-store-url   `s3://quickwit/``.
When receiving a query targetting index_id=wikipedia, the server will dynamically load and cache the meta file in `s3://quickwit/wikipedia/quickwit.json`.

# Url vs Uri

The difference between the two is notoriously confusing. 

[https://danielmiessler.com/study/difference-between-uri-url/#:~:text=The terms “URI” and “,as HTTPs %2C FTP %2C etc](https://danielmiessler.com/study/difference-between-uri-url/#:~:text=The%20terms%20%E2%80%9CURI%E2%80%9D%20and%20%E2%80%9C,as%20HTTPs%20%2C%20FTP%20%2C%20etc).

We do not really use these uri as IDs and it is quite common to consider relative url valid.  Usage is just 50% 50%. Postgresql refers to their  postgresql://... addresses as an url, while amazon s3 referes to s3://...  addresses as an uri.

The following poll suggests uri is more popular.
[https://twitter.com/fulmicoton/status/1397738350270840832](https://twitter.com/fulmicoton/status/1397738350270840832)

Which one do you prefer?

# Alternative solution

I think it is possible to build a consistent spec base on index_uri in place of index_id.

Our current spec is halfway between that imaginary spec and the spec above... This alternative is possible but we need to correctly spec it out.

**Comment by fulmicoton** [comment]
@evanxg852000 @fmassot @mosuka @guilload I'm interested in your opinions and if we roll with it, I need everyone to read that.

**Comment by fmassot** [comment]
Thanks @fulmicoton , this is so much important to clarify theses points.
I'm totally inline with that. I would prefer to keep `URI`stuff for no objective reason... I like it because in my brain, URI is more generic => it's better, but well, that's all :/

A few remarks:
- it's fundamental to have a split_id because I really don't want to manage splits on different storages. I like this consistency.
- for `quickwit serve`, I considered initially that a user can index several indexes on different storages and I was thinking about that just yesterday so your writing comes at the right moment for me. Using an implicit metastore location at indexing can be confusing when you want to serve it... because if you decide to go for two indexes on two s3 buckets, now you're fucked. For me, we need to make it clear that the use have to choose where he will put his metastore at the very beginning and provide a command like this:
`quickwit index --index-uri s3://quickwit/wikipedia --metastore-uri s3://quickwit/metastore_of_all_my_indexes`
Of course, metastore-uri can be optional and in this case it's on s3://quickwit/

**Comment by fulmicoton** [comment]
I'd rather do...
`quickwit index --index-id wikipedia --metastore-uri s3://quickwit/metastore_of_all_my_indexes`


And the metastore would be in charge of telling me what the index-uri is (this needs to be added to the metastore API btw.)

**Comment by fmassot** [comment]
The PR is merged but we need to discuss the last thing on serving index on multiple s3 buckets

**Comment by fmassot** [comment]
> I'd rather do...
> `quickwit index --index-id wikipedia --metastore-uri s3://quickwit/metastore_of_all_my_indexes`
> 
> And the metastore would be in charge of telling me what the index-uri is (this needs to be added to the metastore API btw.)

Yes absolutely, for indexing command, the metastore has already all the information so my point is not relevant on the index command, I think I was targeting the new command in fact.. anyway the PR you merge is perfectly fine as we store the index uri and the index id.
