### ISSUE TITLE
Indexing server

### ISSUE THREAD

**Issue by guilload** [quickwit-inc/quickwit#581]
I've added a `source-config-path` option for the `quickwit index` command but we need something more complete and robust for managing multiple sources/indexers.

**Comment by guilload** [comment]
For this iteration, we want to:
- introduce an index config file format that extensively describes an index (mappings, metastore storage, commit/demux/merge/retention policies, ...)
- introduce a CLI API for adding and updating indexes in the metastore "à la kube": `quickwit index apply ...`
- implement an indexing server that runs a full indexing pipeline for each index described in the metastore
- introduce a CLI API for starting/restarting/stopping an indexing server

The indexing server exposes a few endpoints:
- admin UI
- healthcheck 
- Jaeger
- Prometheus

**Comment by fmassot** [comment]
After a brief discussion with @fulmicoton, here what we can do for the 0.2 release:
- handle multi-source and multi indexes: for each source/index, we start a pipeline.
- provide a simple health check such as the one for the searcher

Let's add Prometheus and admin enpoints for the next release (note: we should ship the next release sooner).
