### ISSUE TITLE
New command infers index-id from the index-uri

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#589]
Right now the index-id is inferred from the index storage uri...

I wonder if this is a good idea?

**Comment by fulmicoton** [comment]
@guilload  @fmassot

**Comment by fmassot** [comment]
This idea came to my mind when I updated the CLI. I like setting the `ID` explicitly, it's clearer for the user. 
And if we set the `metastore-uri` in the context, I think we're good.

**Comment by guilload** [comment]
Assigning to @evanxg852000:
1. add an `index-id` option to all commands and stop extracting the index ID from the index URI.
2. clean up code, i.e., remove functions such as `extract_index_id_from_index_uri`.
3. use env variable `QUICKWIT_METASTORE_URI` as fallback for `metastore-uri`.

Now, one limitation is that for single-file-metastore-backed-indexes, `quickwit serve` can only serve multiple indexes sharing the same parent directory.
