### ISSUE TITLE
More accurate semantics in Storage trait and implementation in the FileStorage 

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#59]
We want the Storage trait to mimick the experience of using an object storage.

Object storage do not have a real notion of a directory.
Put("a/b/c/d") does not require to create the directory "a/b/c" beforehands.

Similarly, removing ("a/b/c/d"), does not mean that we left the directory a/b/c empty.
The directory simply do not exists. It is more of a blob key value store.

The "/" are only characters in a key, that happens to be useful. Listing files in one of those "fake" directory is in fact a prefix enumeration.

- [ ] Clarify this semantics in the Storage trait. 
- [ ] Fix the LocalFileStorage implementation to implement this semantics. Delete can be best effort. If we delete a file that is the last file in the current directory, and it is not the root of the filestorage, try to remove the directory. If removing the directory fails, log a warning, and ignore the error. 
- [ ] Add tests

**Comment by evanxg852000** [comment]
Yep, @fulmicoton I just got hit by this bug. 
It is indeed so important the LocalFileStorage behaves the same way as object storage.

**Comment by fmassot** [comment]
@fulmicoton I think we can close now.
