### ISSUE TITLE
Ensure that the upload-cache is carefully cleaned up on restart

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#615]
For instance, if we kill the indexing process and run GC outside of it, the split files will be removed but will never be removed from the cache.

It would be safer to make sure that upon restart we only keep the published split, and remove all other files.

I think we can do this clean up after every restart of the indexing pipeline. 
Probably upon the creation of the local split store.

**Comment by guilload** [comment]
Implementation pointers:
1. On startup, list the splits in the cache
2. Fetch the state of these splits from the metastore
3. Remove splits that are not in published state
