### ISSUE TITLE
Upload cache should only store splits that are not mature

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#616]
Right now the upload cache will cache everything until they are deleted.
(They are not expiration date.)

Without anything mature splits will just fill up the cache.
Right now we can set a file size limit to help with this, but this logic is very brittle and depends on the data & merge policy settings.

We want to make sure we only cache splits that are not mature.
Extra difficulty: what should we do if the merge policy settings are changed?

**Comment by fmassot** [comment]
There is another thing to take into account. If we are not doing demuxing on a the server. We obviously don’t want to cache splits for that. I will reopen the issue fort that today and check if the code is right.
