### ISSUE TITLE
Add create_timestamp to metastore split 

### ISSUE THREAD

**Issue by evanxg852000** [quickwit-inc/quickwit#665]
It would be nice to have  `create_timestamp`  added to split in the metastore. This will help in debugging and monitoring.
As a bonus, one could use the Diesel ORM trigger feature for keeping both `create_timestamp` and `update_timestamp` in sync automatically

**Comment by fulmicoton** [comment]
Had to reverse the PR as it broke backward compatibility.

@evanxg852000 can you fix and resend a merge request?
