### ISSUE TITLE
Search succeeds with 0 hits if credentials for S3 are set incorrectly

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#667]
It happened with the metastore on amazon s3. The metastore was accessible.

**Comment by fmassot** [comment]
Mmmm, I will need your help to dig into this issue as I did not manage to reproduce it, I got some storage errors.

Can you confirm the following info:
- start a server on ec2 with a metastore on s3 which is accessible
- index-uri is on s3

How did you set the aws credentials?

**Comment by fmassot** [comment]
Closing in 7 days if no sign of activity :)

**Comment by fulmicoton** [comment]
Reassigned to myself

**Comment by fulmicoton** [comment]
Testing search service with a postgresql metastore.

**Comment by fulmicoton** [comment]
Closing
