### ISSUE TITLE
Commit policy num docs parameter & max merge doc should be merged? 

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#683]
Right now we can have a num docs > max doc in the merge policy.
related to #678

**Comment by guilload** [comment]
#836 merged the two parameters. Current naming `split_max_num_docs` is somewhat misleading though. Do we want to rename the parameter to something like `split_num_docs_target`?

**Comment by fmassot** [comment]
+1

**Comment by guilload** [comment]
Closed via #868.
