### ISSUE TITLE
Inconsistent split state in postgresql

### ISSUE THREAD

**Issue by fmassot** [quickwit-inc/quickwit#698]
We save twice the split state information: in a dedicated column and also in a text field (json).

Here is the output of a select on `splits` table:

```
split_state | split_metadata_json
Published   | {"split_metadata": {..."split_state":"Staged",...} }
```

It seems to be the case for many splits.

**Comment by fulmicoton** [comment]
@pseitz can you have a look at this ticket ? (First check that it is not too much of slippery slope)
