### ISSUE TITLE
Demux should be able to run on a dedicated server

### ISSUE THREAD

**Issue by fmassot** [quickwit-inc/quickwit#699]
It's possible to run demuxing without merge but we need to take care of the following stuff:

1. we should have a flag `--demux` in our CLI to indicate that we want the demux to run
2. the planner needs to be updated by new merged splits produced by the indexing. At short term, running a job periodically should be sufficient to take care of that.
3. the job should run as long as there are some demux operations to make. This is not the case currently, once the source is exhausted, we shut down the pipeline.

**Comment by fmassot** [comment]
The first point is resolved in #707

**Comment by fulmicoton** [comment]
@fmassot I don't think it is necessary for Quickwit 0.2. Can we move this out of the quickwit 0.2 project?
