### ISSUE TITLE
Create an S3 compatible metastore

### ISSUE THREAD

**Issue by evanxg852000** [quickwit-inc/quickwit#70]
Currently, the index command of quickwit-cli can only be used with `--index-uri file://`.  Any other protocol is raised as an UnsuportedProtocol error. 

We need to implement a Metastore that interacts with s3 storage interface.

We could also make SingleFileMetastore supports the s3 protocol.

**Comment by fmassot** [comment]
Ok the simplest thing to do is delete the MetastoreUriResolver for now and just use directly SingleFileMetastoreFactory

**Comment by fmassot** [comment]
@evanxg852000 we can close I guess ?
