### ISSUE TITLE
Run connectivity test on startup

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#701]
It seems like a good 80% of the friction experienced by quickwit users are related to the proper configuration & connectivity of third-part services (source, store, metastore).

Right now, we surface these error of configuration only when they occur. For instance, if the credentials for the storage are wrong, indexing will fail after running for 30s, with a message that is relatively explicit for us, but might lack a bit of context for the user. 

Instead, we should have a nice way to test connectivity first and output a report stating clearly what piece of the puzzle is not configured correctly.

For the CLI, it would materialize in a familiar checklist list UI for instance.

----
- source  ❌
  <some extra informaiton>
- storage ✔️ 
- metastore connection ✔️ 
- index configuration ❌
  <some extra information>
-----

And all error details. 

This functionality is VERY likely to be reused in the near-future in an admin UI.
A little bit of overengineer does make sense here.

Typically, we should have a function taking some configuration as an input and returning the connectivity results as some structured object containing all the information necessary for reporting.

Printing this object as checklist will be done in a different function.

**Comment by llogiq** [comment]
The description mentioned 4 checks: source, storage, metastore connection and index configuration.

1. What is source? Would that be the wikipedia file in our example?
2. what checks are needed with regards to index config? Just validity?
3. Is "storage" the index storage (so `file://$(pwd)/wikipedia` in the quickstart example)?

**Comment by fmassot** [comment]
Let me give some details:
1. The source is defined [here](https://github.com/quickwit-inc/quickwit/blob/main/quickwit-indexing/src/source/mod.rs#L64-L95). It produces batches of documents that the indexer will index.
2. Index configuration: I see validity yes but not sure if there is something else to check, @fulmicoton any thoughts on this? 
3. "Is "storage" the index storage " I think yes in this case, we are talking about index storage. But let me give you some details about how storage can be used in quickwit: it can be used either for the index storage or for the metastore when the metastore is a single file metastore. But in this case, we would want to check the metastore storage when checking the metastore.

**Comment by fmassot** [comment]
For the wikipedia example, you need 2 things:
- a [index config file](https://github.com/quickwit-inc/quickwit/blob/main/examples/index_configs/wikipedia_index_config.json) which defines the index schema
- and some data to index, that's the source, it can be a json file or a kafka topic. To start indexing, you will need to pass in the CLI argument a data source file, like this one:

```json

{
    "source_id": "my-file-source",
    "source_type": "file",
    "params": {
        "filepath": "your-path-to-wikipedia-json-file"
    }
}
```

**Comment by llogiq** [comment]
Ok, I've had a look around the code, and it seems if there's any checking at all, then it's incidential as part of the normal operation. For example, the IndexConfig is checked by serde deserializing  a `DefaultIndexConfigBuilder` from JSON and casting any errors to `anyhow::Error` via `?`.

So my suggestion to tackle this would be to introduce `fn check(..)` methods in some spots (e.g. the `Source` and `Metastore` traits, and the `CreateIndexArgs` struct for config), those can be re-used from other places (like the supervisor) as well. We can then create a global `fn startup_checks()` method that can call all the checks either in order or asynchronously, whichever you prefer.

**Comment by fmassot** [comment]
On the index configuration side, I now remember some things that lead @fulmicoton to add this part. 
Let's take some examples:
- a user makes a search query that is not valid regarding the index. It could happen with phrase queries on an index that does not have positions indexed. Let me explain how the query is processed by the server that receives the query. This server acts as a root and distributes the search on every splits (= a piece of the index) to leaf nodes and aggregate the results and finally return that to the user. Each node will evaluate the query and in this case of a phrase query on an index with no position indexed, it will always fail. This is not very efficient as from the root server we could have known that the query was bad. 
- in the same spirit, we could check also parameters validity on the search stream endpoint: in this case we need to check if `fastField` and `partitionField` are fast field and both u64 or both i64.

**Comment by fmassot** [comment]
One more thing to give you more understandings about this issue comes up. The main problems we had happened when running 2 commands:
- `quickwit index --index-id $INDEX_ID --metastore-uri $METASTORE_URI...`: this command launches the indexing and it's important to check the metastore, the index storage, the source connectivity before starting indexing. 
- `quickwit serve`: this command starts a search server, can be a cluster if you add some peer seeds. In this case, it's important to know that the server can respond to queries on different indexes. So basically here, when starting the server, we can just make sure the metastore connectivity is ok and that's all. It will not be efficient to check the connectivity of all indexes present in the metastore. When a user makes a query, we go back to the example above and here we want to check if the query is consistent with the index schema.
