### ISSUE TITLE
Pipeline termination

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#702]
Quoting Francois on our condition to stop the pipeline.

> A related remark on the merge pipeline termination. When indexing is ended mostly because the source is exhausted, there can still have some merges to do. So why not stop when there is no merged operation left and when indexing is stopped?

That's an excellent question. What is the best spec is not entirely trivial but I think you are right.
Here are the options
- a) when there are no more message stop and cancel pending merge
- b) when there are no more msg, finish the currently running merge but do not start extra merges.
- c) when there are no more messages keep merging, including merge candidates that were added recursively.

a) has had some bad effect on tantivy-cli users (there is an option to do c though.
The problem is that if people have a cron job to index small batch of docs, it is possible that no merge ever terminates.

I think b) and c) make sense. They have the demerit of increasing the overall runtime in an unexpected manner.
(I don't get it usually it finishes in 20s but sometimes it takes 5mn)

**Comment by fmassot** [comment]
I will start with the user's expectations:
1. a user wants to start an indexing server that starts pipelines 
2. a user wants to index a source that never stops like a Kafka source
3. a user wants to index one file and have a full and optimized index
4. a user wants to periodically launch a demux job
5. a user wants to launch a merge job after changing the merge policy

Today we are covering the need 2). What about the other cases?

For the 1), I would expect that the pipeline stop when all demux & merges operations have finished as I don't really care about the overall time, my indexing server is running and it will not stop.
For the 4) and 5), we can provide CLI commands to do all merge operations and demux operations. This provides some flexibility to the user once he has indexed its dataset.

For need 3), the user is not launching a server, it's just a job and we can pass some argument to indicate to do all the merge operations or not.


### Conclusion
On the indexing server, I would expect the pipeline to terminate once all merge operations are done, the c).

For jobs, I think we can add some extra arguments to indicate when to stop. By default I would do b) and a flag can force to make all merge operations.

**Comment by fmassot** [comment]
Here is another termination path for the pipeline:
- The source is exhausted => it exits
- The indexer exits too as no other actor has a reference on his mailbox
- Same for packager and uploader
- Publisher on finalizing send an exit message to the merge planner + garbage collector
- the merge planner ends sending current merge operations and exits
- the other merge pipeline actors exits too

And what I'm describing here is in the fact the current implementation! So we have nothing to do.

One last thing, I saw that we only send one merge operation per merge level, we may want to send all merge operations for all levels.

**Comment by fmassot** [comment]
@fulmicoton it seems that I overthought about this issue and that we have nothing to do except send all merge operations. I don't know why you chose to send only one merge operation per level. For demuxing, I send all of them.

**Comment by fmassot** [comment]
Closing as we have now an indexing server that spawn a merge pipeline with a vec source that will exhaust immediately #993

**Comment by fulmicoton** [comment]
The idea there is that if you queue 2 operations, then you lose an opportunity. At the time when operation 1 finishes, maybe the set of splits have changed and your original choice is now suboptimal.

That being said... I don't know why I decided to pick one per level as opposed to one overall. Maybe the lowest level should go first?
