### ISSUE TITLE
Unify the way we show color in the terminal.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#710]
Right now we show color in the indexing stats and in the demux stats.

Both are relying on different dependencies.
In addition, the demux stats stuff always shows color no matter what.
The indexing one checks whether it works in a TTY and shows colors only in that case.

We need ot use the same dependency anywhere, and ideally  do not show color if not in TTY.
Ideally we might want a generic cli arg to disable color regardless of whether we are in TTY or not.
(For instance it can be useful when using nohup)

**Comment by fmassot** [comment]
closed in #709
