### ISSUE TITLE
Broken unit test test_proptest_simulate_demux_with_huge_tenants

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#712]
thread 'actors::merge_executor::tests::test_proptest_simulate_demux_with_huge_tenants' panicked at 'Input split num docs must be `>= min_split_num_docs * output_num_splits`.', quickwit-indexing/src/actors/merge_executor.rs:641:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'actors::merge_executor::tests::test_proptest_simulate_demux_with_huge_tenants' panicked at 'Input split num docs must be `>= min_split_num_docs * output_num_splits`.', quickwit-indexing/src/actors/merge_executor.rs:641:5
thread 'actors::merge_executor::tests::test_proptest_simulate_demux_with_huge_tenants' panicked at 'Input split num docs must be `>= min_split_num_docs * output_num_splits`.', quickwit-indexing/src/actors/merge_executor.rs:641:5
thread 'actors::merge_executor::tests::test_proptest_simulate_demux_with_huge_tenants' panicked at 'Input split num docs must be `>= min_split_num_docs * output_num_splits`.', quickwit-indexing/src/actors/merge_executor.rs:641:5
thread 'actors::merge_executor::tests::test_proptest_simulate_demux_with_huge_tenants' panicked at 'Input split num docs must be `>= min_split_num_docs * output_num_splits`.', quickwit-indexing/src/actors/merge_executor.rs:641:5
thread 'actors::merge_executor::tests::test_proptest_simulate_demux_with_huge_tenants' panicked at 'Input split num docs must be `>= min_split_num_docs * output_num_splits`.', quickwit-indexing/src/actors/merge_executor.rs:641:5
thread 'actors::merge_executor::tests::test_proptest_simulate_demux_with_huge_tenants' panicked at 'Input split num docs must be `>= min_split_num_docs * output_num_splits`.', quickwit-indexing/src/actors/merge_executor.rs:641:5
thread 'actors::merge_executor::tests::test_proptest_simulate_demux_with_huge_tenants' panicked at 'Test failed: Input split num docs must be `>= min_split_num_docs * output_num_splits`.; minimal failing input: tenants_num_docs = [10001]

**Comment by fmassot** [comment]
strange, I run the test on main branch and it's working. The test was failing on the previous commit though and then I fixed it.

**Comment by fmassot** [comment]
ok, this is not a bug, it's just the test that is stupid and gives wrong arguments to the `demux_virtual_split` that is failing as expected. I will remove this dumb test and add a real one.
