### ISSUE TITLE
Reorganize CLI subcommands

### ISSUE THREAD

**Issue by guilload** [quickwit-inc/quickwit#722]
Currently, the CLI is a flat list of commands such as `new`, `index`, `search`, `serve`, `inspect-split`, `stats` (demux), ... As this list is growing longer, a nested structure might be more suitable. For instance:

```bash
quickwit index apply / list / delete
quickwit split add / list / delete
quickwit service ...
```

**Comment by fmassot** [comment]
## Commands organization

To have a nice CLI, we need to organize all the commands in a hierarchical way, with commands, subcommands, sub subcommands, etc.

Let's list of the root commands we want: 
- `index`: manage indexes in the metastore, crud operation basically. But also can be a move between storage like "ok I want to move this local index to s3".
- `split`: manage splits of an index, crud operations.
- `service`: this command will start a service (only one a priori), the search server, the indexing server. In the future, we may have a metastore server and an ingester.
- `job`: it could be useful to have a bunch of job commands to do some maintenance stuff, like merging, demuxing, cleaning a index (still don't know what cleaning will do ;))
- `stats`: a command to get some stats about anything: today we have the demux stuff, could be also about merge operations.
- `tutorials`: a command that creates and indexes some data of a tutorial present in the docs. 

On the naming, there is a question about using the plural or the singular, I'm not sure what's the best here. Singular for service as we will start one service, but it makes sense to use plural on index and split.

All commands require a metastore uri argument, we will omit it here for clarity. Moreover, the goal is not to write down all arguments but have a good list of all commands. 

### Index

- create or update the index config from a config file. 
`quickwit index apply -f <path-to-index-config-file>`

- (not for today) show list of indexes in the metastore. Currently, the metastore API does not provide such an API.
`quickwit index list`

- delete an index
`quickwit index delete <index-id>` 

- (not for today) move an index to another index-uri
`quickwit index move <index-id> <new-uri>` 


### Split

- add a split from an existing split file. 
`quickwit split add --index-id <index-id> -f <path-to-split>`

- (not for today) show list of splits for a given index. 
`quickwit split list --index-id <index-id>`

- delete a split
`quickwit split delete <split-id> --index-id <index-id>` 

### Service

- Start search server
`quickwit service start search`
- Start indexing server
`quickwit service start index`

### Job

`quickwit job demux --index-id <index-id>`
`quickwit job merge --index-id <index-id>`

### Stats
TODO

### Tutorials
TODO

**Comment by fmassot** [comment]
# Noun + verb
![Capture d’écran 2021-11-16 à 22 40 11](https://user-images.githubusercontent.com/653704/142071078-8c820ad3-d358-4e8d-8d57-a2d50e4f59ef.png
)

# Verb + noun
![Capture d’écran 2021-11-16 à 22 45 49](https://user-images.githubusercontent.com/653704/142071086-4e474b1a-a8dd-497c-8592-381b661cae39.png)
)
