### ISSUE TITLE
The "getting started" document is missing some things

### ISSUE THREAD

**Issue by llogiq** [quickwit-inc/quickwit#737]
**Describe the bug**

**Steps to reproduce (if applicable)**

Following the `quickwit new` command from the [getting started](https://quickwit.io/docs/getting-started/quickstart/#create-your-first-index) document, I get the following error:

```console
$ quickwit new --index-uri 'file://${PWD}/wikipedia' --index-config-path ./wikipedia_index_config.json
error: The following required arguments were not provided:
    --index-id <INDEX ID>
    --metastore-uri <METASTORE URI>
```

**Expected behavior**
The document should describe the new arguments and provide suitable defaults.

**System configuration:**
Quickwit 0.1.0 (commit-hash: 1909672) on voidlinux 5.13.19_1 #1 SMP Sat Sep 18 18:18:26 UTC 2021 x86_64 GNU/Linux, Ryzen 3550H, 8GB RAM

**Comment by llogiq** [comment]
I can solve this particular problem by calling `quickwit new --index-uri file://${PWD}/wikipedia --index-config-path ./wikipedia_index_config.json --index-id wikipedia --metastore-uri file://${PWD}/metastore/`.

I'll send a documentation update PR once I've finished going through the document.

**Comment by fmassot** [comment]
@llogiq good point, we did not update the docs since the last release in July...

**Comment by llogiq** [comment]
@fmassot You should make sure that the PR is merged before the next release, but not published to the website before that.

**Comment by fmassot** [comment]
@llogiq yes no problem with merging that, for the moment the docs are generated manually when we update the website.

**Comment by wathiede** [comment]
Should [docs/tutorials/tutorial-hdfs-logs](https://quickwit.io/docs/tutorials/tutorial-hdfs-logs) be updated similarly?

**Comment by fmassot** [comment]
@wathiede it should but we are currently changing the format and the change will be effective in a few weeks. We will very soon update all the docs.
