### ISSUE TITLE
cli.yaml is not sync with the parsing

### ISSUE THREAD

**Issue by fmassot** [quickwit-inc/quickwit#749]
At least there is one argument which is present in [cli.yaml](https://github.com/quickwit-inc/quickwit/blob/main/quickwit-cli/src/cli.yaml) and is not parsed: `num-thread`

We could fix that in #722 as we will revamp the CLI in this issue. 

As suggested by @fulmicoton we may want to remove it.

**Comment by fmassot** [comment]
Mm actually, the yaml file is important so I think we should keep it. Not sure if you want something else in mind @fulmicoton

**Comment by guilload** [comment]
Yeah, in my opinion, relying on the YAML file is the least painful way of to set up a clap CLI.
