### ISSUE TITLE
Set default values for `IndexConfig`

### ISSUE THREAD

**Issue by guilload** [quickwit-inc/quickwit#756]
Currently, all the options are mandatory. However, some should be optional, and we should provide sensible default values. For instance, `demux_field`, `timestamp_field`, `commit_timeout_secs`, `split_max_num_docs`, ...

@fmassot @fulmicoton
What are good default values for:
- `commit_timeout_secs`: 60s?
- `split_max_num_docs`: 10M?
- `merge_policy`?
- `store_source`: true?

Should we provide a default value for indexing resources?

**Comment by guilload** [comment]
@evanxg852000, reassigning to myself as I'm tackling this issue as part of https://github.com/quickwit-inc/quickwit/compare/guilload--index-metadata-v1

**Comment by fmassot** [comment]
- `demux_field` and `timestamp_field` are optional
- `store_source: true` is a good start as a user will be happy to see some results
- `split_max_num_docs: 10M` LGTM
- The default parameters of the current `merge_policy` are good I think, I would only change `demux_factor` to 8.

**Comment by guilload** [comment]
Thanks. Changing `demux_factor` to 8, and we're good to go. On the indexing resources side, I arbitrarily went with one thread and 2GB of memory.

**Comment by guilload** [comment]
Also, I wonder whether we should expose users to `min_level_num_docs`?

**Comment by fmassot** [comment]
Good point, I would avoid exposing it, I think we could later even drop it or maybe define it with `split_max_num_docs / 100`.

**Comment by guilload** [comment]
Implemented as part of #836.
