### ISSUE TITLE
We are we running search in a Tokio async task O_O

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#785]
In regular search, we are currently running on a regular tokio runtime thread.
In stream, we are running in a tokio spawn_blocking thread but we forgot to set the number of such worker to the number of CPUs.
![f87cfb2faefca548464cd6e485ceef9a](https://user-images.githubusercontent.com/1021506/142148855-4acc1299-e43f-421d-a4ce-d6d209695c7b.gif)

**Comment by fmassot** [comment]
Can you put a link to the code? (Is it the cli? A search query?€

**Comment by fulmicoton** [comment]
I'll send you a PR soonish.
