### ISSUE TITLE
When using the stream API if no field is given we return a cryptic error.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#791]
The check should be done when we parse the arguemtn in the rest API.  (fastField is required)
```
error=Internal error: `Invalid query: Field `` does not exist in schema`
```

**Comment by fmassot** [comment]
Issue fixed by #b0cdfb4
It's not perfect though as error message coming from serde are not user friendly. We may want to use a crate like https://github.com/Keats/validator in the future.
