### ISSUE TITLE
Need timestamps fields on index 

### ISSUE THREAD

**Issue by evanxg852000** [quickwit-inc/quickwit#797]
We currently have `create_timestamp` & `update_timestamp` on the Split, we would like to have the same field for the Index

**Comment by evanxg852000** [comment]
@guilload I am wondering if there was any reason you added  `create_timestamp` to IndexMetadata, but not `update_timestamp`?
- Also, do we want to keep this in sync with its child splits, that is `IndexMetadata.update_timestamp` should change when any split of the index is modified?
- Can we pull apart the fields in the PgSQL model as opposed to currently bundling them into `index_metadata_json`? I think this depends much on the previous question. 

@fulmicoton @fmassot any take

**Comment by guilload** [comment]
I decided not to do it as part of #836 because the PR size was already unmanageable. Your suggestion is a good idea, but I don't know if we want to go as far. I'll let @fmassot and @fulmicoton weigh in.

**Comment by fulmicoton** [comment]
Either way is fine with me.
