### ISSUE TITLE
Are we comfortable with `{update,create}_timestamp` default?

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#799]
Are we comfortable with `{update,create}_timestamp` default?
Right now they default with 0.

Shouldn't we default to now() ?
I am not sure what the implication are to be honest.

**Comment by evanxg852000** [comment]
I felt more comfortable to default them at zero as to make a difference between those timestamps that default from DB `now()` to those that had no timestamps at all from the DB. Currently only the `update_timestamp` field is used to filter in splits that fall out of the grace period during garbage collection. The rest is for monitoring, Maybe a `-1` could also be a candidate.

**Comment by PSeitz** [comment]
0 reads to me like either the split has never been created or updated.
Does this value only occur for old splits from a previous version?

**Comment by evanxg852000** [comment]
Previously we had `update_timestamp` as `BIGINT DEFAULT 0',  however, this was just a default from the DB point 
all operations were setting it to `NOW()`.
Currently, we have changed the type to `TIMESTAMP` and added `create_timestamp` as a new field.

**Comment by fulmicoton** [comment]
I think UTC::now() would have been more correct... But at this point we do not really care anyway.
What do I mean by more correct?

Right if there is a search query running and we migrate the index, we might GC splits that were in the middle
of the query, and the query might fail.

Not likely to happen in the current situation, but still ill advise.
Closing
