### ISSUE TITLE
Standardize quickwit env variable

### ISSUE THREAD

**Issue by fmassot** [quickwit-inc/quickwit#811]
Currently, some environment variables have the prefix `QUICKWIT_`, some don't.

We should keep the same standard everywhere.

**Comment by fatelei** [comment]
let me try

**Comment by fmassot** [comment]
@fatelei you can :)
don't hesitate to come to our discord server to discuss about it.

**Comment by fulmicoton** [comment]
Keep in mind a lot of those are planned to move into configuration files though.

**Comment by fatelei** [comment]
ok，refactor it using config file

**Comment by fulmicoton** [comment]
I assigned you the ticket but please give us a couple of days to flesh out a good ticket description!

**Comment by fulmicoton** [comment]
After further investigation we decided to move all of the env variable to the configuration. Closing the issue!

**Comment by fatelei** [comment]
so，i submit a configuration design doc?

**Comment by guilload** [comment]
Hi @fatelei,

This is already work in progress. I'll open two PRs in the next coming days. I can tag you in them if you're interested.
