### ISSUE TITLE
Add real size of the split in the split metadata

### ISSUE THREAD

**Issue by fmassot** [quickwit-inc/quickwit#815]
Currently, we have `size_in_bytes` in `SplitMetadata` to have an idea of the split size but it corresponds to the size of the original
JSON payloads.

It would be useful to have the real size of the split.

**Comment by PSeitz** [comment]
We have it as part of the footer offsets.

We could consider renaming size_in_bytes in https://github.com/quickwit-inc/quickwit/pull/789, since it will be a new version anyways.

**Comment by fmassot** [comment]
ah yes! Not sure if it's good to change the names, keeping `offset` is not bad.
