### ISSUE TITLE
Replace usages of `String` and `Path` with custom URI type

### ISSUE THREAD

**Issue by guilload** [quickwit-inc/quickwit#834]

**Comment by guilload** [comment]
Thoughts for the API?

```rust
implement Uri {
  pub fn protocol(&self) -> Protocol;
  // Your ideas here...
}

**Comment by evanxg852000** [comment]
@guilload  so my idea about these two methods was that :
Uri::cannicalized_path() -> would check if the path exist 
Uri::normalized_path() -> would just normalise without checking.

But we can just have `normalise` and whoever need to check will do its check.

**Comment by guilload** [comment]
Here are a few thoughts:
- URIs should always be normalized;
- URIs can only be instantiated with the `try_new` constructor, which performs the normalization;
- `Path` only makes sense for the `file` protocol, so `.path()` should return an Option<&Path>
- Let's return reference types such as `&str` or `&Path`, and users can convert them to owned types if necessary.

There are many ways to implement this; here's my take. I'm sure @fmassot, @fulmicoton @PSeitz will have suggestions:
```rust
pub struct Uri {
    uri: String,
    protocol_idx: usize,
}

impl Uri {
    pub fn try_new(uri: &str) -> anyhow::Result<Self> {
        unimplemented!()
    }

    pub fn protocol<'a>(&'a self) -> &'a str {
        &self.uri[..self.protocol_idx]
    }

    pub fn to_str<'a>(&'a self) -> &'a str {
        &self.uri
    }

    // Maybe?
    pub fn into_string(self) -> String {
        self.uri
    }

    pub fn to_string(&self) -> String {
        self.uri.clone()
    }

    pub fn path<'a>(&'a self) -> Option<&'a Path> {
        if self.protocol() == "file" {
            self.uri.strip_prefix("file://").map(Path::new)
        } else {
            None
        }
    }
}
```

**Comment by evanxg852000** [comment]
@guilload I have a draft PR you can already look at.
I refrained from changing the type of things like `IngestDocsArgs::metastore_uri` from `String` to `Uri` till
we are sure about the API. 
I tried to avoid lifetimes from your suggestions. 
Also I think following the concept of URIs,  the method `Uri::path` should always return a path no matter the protocol, that path will be fs::normalized for `file://`

**Comment by fulmicoton** [comment]
The ticket is a great idea.
I added a bunch of comment in Evance's PR.

I think we should stick to Adrien's idea of keeping the protocol offset index.
