### ISSUE TITLE
Consider refactoring checkpoints serialization

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#837]
As raised by @guilload ...
With multisource, we probably need one way or another to namespace our checkpoints's position.

(whoever takes this ticket, make sure you open a discussion first on what should be done, and have a thought about backward compatibiity)

**Comment by fmassot** [comment]
Very good remarks.

Maybe we could first start with delete/add a data source. 

Having a checkpoint reset is nice too. See [druid docs](https://druid.apache.org/docs/latest/development/extensions-core/kafka-ingestion.html#resetting-supervisors).

**Comment by fmassot** [comment]
As discussed with @fulmicoton I'm in favor of having a map of `<SourceId, Checkpoint>` in the `IndexMetadata`.
It would be nice also to isolate the checkpoint in a dedicated table `checkpoint` with columns `source_id`, `partition_id`, `position`.

**Comment by guilload** [comment]
Yeah, going with a map from `SourceId` to `Checkpoint` is the natural way. I was going to suggest moving the checkpoint to a dedicated column but I see how a dedicated table has some additional advantages.

As a checkpoint is strongly tied to a source, I suggest we go a step further and go with a dedicated source table with a checkpoint column instead.

**Comment by fulmicoton** [comment]
Keying on the SourceId might not be a good idea.. At least with our current vision for the definition of source.

Here is why:
Right now when indexing a topic with a lot of partiition our idea for distributed indexing is to somehow split (staticallly first, dynamically in the future) the list of partitions of the topic amongst N sources.
The N sources can then be indexed entirely independantly.

Rebalancing the partition is then a no-brainer.
We can just reconfigure the list of partition ids and restart.

If we start keying checkpoints with the source id, rebalancing partitions becomes difficult.
