### ISSUE TITLE
Consideration of node discovery using P2P technology

### ISSUE THREAD

**Issue by mosuka** [quickwit-inc/quickwit#84]
Currently, we are doing the node discovery by polling DNS entries in Kubernetes.
However, it takes a few seconds after a new node is added before it becomes available.
So, we will try to create a sample project to consider if it is possible to do the node discovery more easily using P2P technology.

**Comment by fulmicoton** [comment]
For various reasons I am not fond of the idea of using libp2p. 
It seems designed for a totally different use case.

The standard algorithm for cluster membership is called SWIM. It detects failing nodes and propagates the information.
The most robust implementation is [from hashicorp, and is written  in golang](https://github.com/hashicorp/memberlist)

**Comment by fulmicoton** [comment]
Also there is a misunderstanding...

The main reason why we cannot rely on DNS discovery like we did in barrel, is because quickwit needs to work in and outside of kubernetes.

**Comment by mosuka** [comment]
Thank you for the detailed explanation.
I will check them out.

**Comment by fmassot** [comment]
Closing this isssue as the target is the SWIM protocol.
