### ISSUE TITLE
quickwit service stop not implemented

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#847]
`quickwit service` stop is not implemented.

I think we need to sort out what is the purpose of this function generally speaking.
My 50c.

The name service and the idea of starting and stopping suggest a daemon (today it is not a daemon but I am not sure what the intent is).

I don't think this is a good idea to have daemonizastion within the binary.
Nowadays it seems more trendy to have a normal binary and leave to the user the choice of how the binary should be run.

A traditional linux service for instance will be run with systemd. The start command is just running the binary and stopping is done by sending a SIGTERM to your binary, and a SIGKILL 60s later if the process hasn't gracefully quitted.

**Comment by guilload** [comment]
Onboard with `quickwit service run`, the example you give for `systemd` is also applicable for Docker where the process runs undetached in the container. Managing the lifecycle of the container is left to the orchestrator.

**Comment by guilload** [comment]
Closing the issue as we settled on `quickwit service run` and the command was implemented.
