### ISSUE TITLE
Index command new behaviour

### ISSUE THREAD

**Issue by fmassot** [quickwit-inc/quickwit#849]
With the new index config, what should we expect from the `quickwit index index` command?

I see 2 questions coming and @guilload already have raised them:
- should we index the sources defined in the index config?
- should we keep offering to index an input file? 

At first, it seems that indexing the sources from this command is no more relevant, why not just start an indexing server? The indexing server is even more relevant when we are indexing from a Kafka source, the `quickwit index index` will run indefinitely in this case and it is thus doing the same thing as the indexing server.

From a user point of view, the `quickwit index index` seems relevant for testing or for some kind of job where you just want to index from a file or from stdin. It would be better to have a command that has an end and doesn't run indefinitely.

So why not move from `quickwit index index` to a `quickwit index ingest` where we can only index a file or data coming from the stdin? And we can add a constraint such that the sources provided to the CLI must not be already defined in the index config.

**Comment by guilload** [comment]
We decided to rename `quickwit index index` to `quickwit index ingest`. This command reads JSON docs from file or stdin. For indexing from a source defined in the index config, the correct command is `quickwit service run indexer`.

Implemented as part of #836.
