### ISSUE TITLE
Remove or hide DocMapperType

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#85]
Right now the role of DocMapperType is a bit difficult. It's only role is to help serialize. Right now the type is too visible.

We could hide it more, or even remove it and rely on typetag.
https://github.com/dtolnay/typetag

**Comment by fmassot** [comment]
very good point, when discussing about the doc mapper with @evanxg852000 it was indeed a confusing to have the choice between the two. Ideally, it would very nice to remove it, I didn't know typetag!!!!! sounds great.

**Comment by fmassot** [comment]
closing thanks to PR #46
