### ISSUE TITLE
Special _tags field may not be needed

### ISSUE THREAD

**Issue by evanxg852000** [quickwit-inc/quickwit#850]
The internal `_tags` field used to store tag values may not be needed.
This task is to discuss and reevaluate the relevance of having this field and possibly getting rid of it depending on the discussion outcome

**Comment by fmassot** [comment]
Let's do a little bit more on this issue. We also need to put some constraints on the type of field that can be added to `tag_fields`.

We want only to tag these types:
- u64, i64, f64, date
- str with raw tokenizer only

I don't see the point of supporting the bytes type.
