### ISSUE TITLE
Update Packaging & installation script

### ISSUE THREAD

**Issue by fmassot** [quickwit-inc/quickwit#852]
# Old way 
`curl -L https://install.quickwit.io | sh` just download quickwit binary and that's it.

# New way

We want to do more today to help the user starts a server quickly with a basic config.

## User journey 
1. `curl -L https://install.quickwit.io | sh` 
2. Ask the user if he is ok with the default installation or change default parameters
3. Install
  - create directory `$HOME/$QUICKWIT_HOME`, by default it's `quickwit-version-number`
  - in the directory, we put the following files:
    - the binary `bin/quickwit`
    - a default server config `config/server.toml`. The default datadir can be `/var/lib/quickwit/data` and logs in `/var/log/quickwit`
    - a tutorials directory which contains the tutorials config files 

The default installation parameters are:
-  $QUICKWIT_HOME = $HOME/`quickwit-version-number` 
- Add `$QUICKWIT_HOME/bin` in his path

**Comment by guilload** [comment]
Looking at what other programs are doing in a user's home directory (`cargo`, `rustup`, `steam`, ...): I'd like to amend the spec:
- Quickwit home directory: `$HOME/.quickwit`
- Bin directory: `$HOME/.quickwit/bin`
- Config directory: `$HOME/.quickwit/config`
- Install release x.y in `$HOME/.quickwit/quickwit-x.y`
- Symlink  `$HOME/.quickwit/quickwit-x.y/quickwit` to `$HOME/.quickwit/bin/quickwit`

Optionally:
- Remove earlier versions
- Offer to symlink `$HOME/.quickwit/bin/quickwit` to `/usr/local/bin/quickwit`. I don't think our binary is so important that it deserves to be added to the PATH.

**Comment by fmassot** [comment]
I like your modifications. I suggested at the beginning to go for the hidden directory but I found hidden directory makes sense especially for mainstream binaries.

**Comment by fulmicoton** [comment]
I'll add we need a strong story for the user who wants to run two server on the same machine. This is very common for testing / development.

I'd go for the following: what we deliver is a .tar.gz package that can be unpacked anywhere.


```
quickwit-VERSION/ <--- That's quickwit home
      bin/
           quickwit   <--- the quickwit binary. 
                                 If QUICKWIT_HOME env variable is not set, use its `own path/../..`
      conf/    <--- I would have put the node local config stuff. What you have today in ServerConfig, IndexerConfig. The conf could give path relative to the QUICKWIT_HOME.
                        The cli keeps its current logic,
                         but just default to `QUICKWIT_HOME/conf/server.yaml` or `QUICKWIT_HOME/conf/indexer.yaml` if is not supplied
            indexer.yaml <--- default indexer config
            server.yaml  <--- default server config
      data/    <--- will receive the default fslocaldirectory. We could add a local:// protocol to point to it.
      logs/    <--- receives the logs
```

When running two nodes on the same server, one unpacks the tar.gz in two different directories,
and edits the config independently.

Case for this solution
- we don't hide anything
- yields less tickets (where are my logs, where is the binary, where is my data, low risk of quickwit binary mismatch)
- discoverability of configuration options (the default conf file are there with the possiblity to have commented defaults)
- possibility in the future to define complicated migration scripts?

**Comment by fulmicoton** [comment]
Created a poll about elasticsearch https://twitter.com/fulmicoton/status/1470938152181600256

**Comment by fmassot** [comment]
Agreed on the .tar.gz package.

I just followed the elasticsearch install and it is pretty neat. 

After going through one of our tutorial, I observed the following stuff:
- `metastore-uri` can be defined either via the server config file, env variable and cli argument depending on the usage. I think this is confusing. Why not always use a config file defined in directory `config/quickwit.yml` by default? By the way we could set a default `metastore-uri` to the directory `metastore` for example. This way, running quickwit would be really simple. 
-  I had permissions issues and I needed to server config host key path to make it work
- I need to customize the `index-uri` to make it work. 
- generally speaking, I'm under the impression that a user will ask several times where he needs to put it's index, the metastore, the data dir etc... this is too much.

For starting multiple instances, we can offer 2 ways:
- unpack quickwit .tar.gz in multiple directories and start each instance from each directory with its conf.
- use docker compose like this https://www.elastic.co/guide/en/elasticsearch/reference/7.16/docker.html

**Comment by fulmicoton** [comment]
> metastore-uri can be defined either via the server config file, env variable and cli argument depending on the usage. I think this is confusing. Why not always use a config file defined in directory config/quickwit.yml by default? By the way we could set a default metastore-uri to the directory metastore for example. This way, running quickwit would be really simple.

very good point. I agree.

> I had permissions issues and I needed to server config host key path to make it work
> I need to customize the index-uri to make it work.
> generally speaking, I'm under the impression that a user will ask several times where he needs to put it's index, the metastore, the data dir etc... this is too much.

This seems like very important points, but I did not quite get them. Can you develop?

I suggest we do tar.gz only for the moment and add docker rapidly.
(docker is awesome but requires more reflexion.)

**Comment by fmassot** [comment]
> This seems like very important points, but I did not quite get them. Can you develop? 
One point (the `index-uri`) is described here: #868. 

>  I needed to server config host key path to make it work
By default, it is written in `/var/lib/quickwit/host_key`. I saw that with @guilload and we agreed to write it in the data directory.

> Should we have a default root for indexes (itself defaulting to file://${datadir}/data/)?
Could be a good default and then we can use ` ${index_root}/${index_id}`.

> I suggest we do tar.gz only for the moment and add docker rapidly.
Agreed.

Here is a good default for a quick start on a local machine 
```
quickwit-VERSION/ <--- That's quickwit home
      bin/
           quickwit              <--- quickwit binary
      conf/quickwit.yaml <--- default config used by searcher / indexer / or any cli commands
      data/                        
      data/indexes           <--- default indexes directory
      logs/
      metastore/               <--- default file based metastore directory
```

**Comment by fmassot** [comment]
The default config in `conf/quickwit.yaml` can be overriden by `--config-uri quickwit.yaml`

I replaced `server-config-uri` by `--config-uri` because it would be used for all commands. It corresponds to the general quickwit config file. We can even simplify the name by using `--conf`, I like that as it's really short.

**Comment by fmassot** [comment]
More thoughts on this after the merge of #938 

The directory layout should look like this:
```
quickwit-VERSION/
      quickwit   <--- the quickwit binary. 
      config/quickwit.yaml <--- quickwit config template
      qwdata/ <-- quickwit data directory
```

We discussed adding a README.md or LICENCE.md or tutorials, I think it's only a nice to have and we can skip that. Let's ship a minimalist package.
