### ISSUE TITLE
Use gRPC and discovery ports from server config rather than hardcoded values

### ISSUE THREAD

**Issue by guilload** [quickwit-inc/quickwit#853]
Currently, the gRPC and discovery (SWIM) ports are hardcoded in the searcher to `REST port + 1` and `REST port + 2`. However, with the introduction of the server config, we can configure those ports independently.

Implementation pointers:
- remove functions such as `http_addr_to_grpc_addr` and `http_addr_to_swim_addr` and use values from server config
- add gRPC port to `Member` in `quickwit-cluster` and use that value to connect to peers via gRPC

**Comment by fulmicoton** [comment]
Ideally we want the best of two worlds...

Configurability + defaults defined relative to rest port. Do you know if it is possible with claps?

**Comment by fulmicoton** [comment]
Making everything configurable makes it a pain for the person who want to run two instances on the same machine.

Ideal spec would be:
- required rest port configurable with a default value
- required grpc port configurable with a default value set to rest port + X
- required discovery configurable port with a default value set to rest port

I don't think clap allows this directly.
One way to do it would be to make the grpc port and the discovery port optional and do the default logic as an accessor.

**Comment by fulmicoton** [comment]
Also the issue description might not be clear:

After #836 all these ports are configurable. Unfortunately our current membership algorithm does not make it possible to expose these parameters, so from after we merge 836 and until we implement scuttlebutt quickwit will be broken.

I suggest we stick to the base port logic for the moment.

**Comment by fulmicoton** [comment]
Discussed offline.

There are two issues here.
- how do we avoid breaking things in the SWIM world?
We can't. Let's hide the config parameters temporarily and use the existing logic for the moment.

- Can we have relative defaults as defined above?
This has nothing to do with claps. That's a config parameter. The config already works with an accessor so this is not a problem at all.

**Comment by guilload** [comment]
I'm going to close this issue and open a clearer one for configurable gRPC port.
