### ISSUE TITLE
Cannot start searcher with bad peer seeds

### ISSUE THREAD

**Issue by fmassot** [quickwit-inc/quickwit#862]
When starting a search with config `peer_seeds = [ "quickwit-searcher-0.local:33333", "quickwit-searcher-1.local:33333" ]`
we get this error message:

```
Command failed: failed to lookup address information: nodename nor servname provided, or not known
```

Not sure if it's normal or not.

**Comment by guilload** [comment]
#868 settled on the following approach:
- we skip peer seed addresses that do not resolve;
- if none of the peer seed addresses resolve, we fail.
