### ISSUE TITLE
Add tutorial with search stream for clickhouse

### ISSUE THREAD

**Issue by fmassot** [quickwit-inc/quickwit#877]
For this tutorial, we could use the github archive. 
There is a demo with clickhouse here: https://ghe.clickhouse.tech/#how-to-download-the-data
There is 3.1 billion records but I expect to have only a few hundreds of millions with text. Using quickwit can enhance the experience by making full-text search queries on comments.

Then the tutorial would be about: "Give full text search to your OLAP db".

The other approach is the logs use case.

Any thoughts on this @fulmicoton @guilload ?

**Comment by fulmicoton** [comment]
That's perfect!

Le lun. 13 déc. 2021 à 06:04, François Massot ***@***.***> a
écrit :

**Comment by guilload** [comment]
I've always been keen on the GHE dataset. Go for it.
