### ISSUE TITLE
Handling "too many tags" in a way that allows for schema config change of the set of fieldset.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#887]
We addressed the too many tags problem by simply adding the tag `tag_field:*`, and expanding all tags in the tag filter ast using the rule:

`tag_field:tag_value -> tag_field:tag_value OR tag_field:*`

This works.

However I think there is a smarter way to do this.
What about do not add anything in the metastore if the cardinality of the field exceeds a given limit.

If a tag for a given field is registered on the other hand, we register `tag_field!`.

Finally we expand the tag filter ast using the following rule.

`tag_field:tag_value -> (NOT tag_field! OR tag_field:tag_value)`.

The benefit here is that this approach allow for a change of tag fields in the schema. 

What we lose is the abiilty to prune over the existence of a single doc containing the given field (which is probably not something that we care much about... but we can introduce yet another magic tag to get that back)

**Comment by fmassot** [comment]
Let's take an example with 3 splits and one tag field `tag_field`
- `split_1`: no tag values => metadata contains `tag_field!` 
- `split_2`: one value `tag_field:value`  metadata contains `tag_field:value`
- `split_3`: too many tag values => metadata tags contains only `tag_field:value`

We can see the immediate benefit by adding a tag field like `tag_field_3`:
- `new_tag_field:value` => `(NOT new_tag_field! OR new_tag_field:value)` will match all splits and that's what we want

I did not follow you on this part:
> What we lose is the abiilty to prune over the existence of a single doc containing the given field (which is probably not something that we care much about... but we can introduce yet another magic tag to get that back)

Can you give an example?

**Comment by fulmicoton** [comment]
I would add
- `split_4`: `tag_field` was not configured as a tag field at that point. metadata does not contain `tag_field!`. 

> Can you give an example?
Forget my point. It was not relevant actually.

**Comment by fmassot** [comment]
All right. Let's do that in the 0.2.

**Comment by fulmicoton** [comment]
@r-zenine is making some proper AST for the tag filtering. It should be relatively trivial to do that kind of manipulation.

**Comment by fulmicoton** [comment]
@r-zenine is on a cruisade to handle negation too. The negation will only appear on the leaves.

It is compatible with the solution described in this ticket but 
the transformation rule is NOT the negation of the positive negation rule.

We want:

`not field_a:val_a -> (not field_a!) or (not field_a:val_a)`
