### ISSUE TITLE
Asking to write the host key somewhere where it has not the permission to do it when starting a searcher/indexer

### ISSUE THREAD

**Issue by fmassot** [quickwit-inc/quickwit#892]
The default is `/opt/quickwit/host_key` which can require root access. I don't really like the default.

**Comment by fmassot** [comment]
you're right. So the user should have a write access to `/var/lib/quickwit`. Anyway I should have been more accurate. For testing purpose, I don't really want to need an access there but we could solve that by providing a better default config for tests.

**Comment by guilload** [comment]
We can implement a `SearcherConfig::for_test` creates an instance that points to a temp dir. See `IndexerConfig::for_test`.

**Comment by fmassot** [comment]
Ok you are wasting your time because I'm not accurate tonight... let's close this issue and have a discussion on this thursday.
