### ISSUE TITLE
Pass index-uri in CLI argument when creating an index (and index-id?)

### ISSUE THREAD

**Issue by fmassot** [quickwit-inc/quickwit#896]
I'm writing the GitHub archive tutorial and one thing that is annoying is the fact that you need to put the `index-uri` in the index config. The user can't download the index config file and just create its index. He will have to customize the file to make it work locally. 

1) First solution: a practical way to avoid that is to pass the `index-uri` in argument. I was thinking of adding also the `index-id`.
2) Second solution: we can use a bash command to quickwit replace the `index-uri` value with an env variable.

I like the 1.

**Comment by evanxg852000** [comment]
- Another option I used was to have the user creates the config file with commands like below assuming he is running through the tutorial from the same directory.
```bash
echo "version: 0
metastore_uri: file://$(pwd)/indexes
searcher:
  data_dir_path: file://$(pwd)/datadir
  host_key_path: file://$(pwd)/datadir" > server_config.yaml
```

- Also if this is only for tutorial files we are bundling with the installation, we could have a script in QUICKWIT_HOME/init_tutorial.sh that will ideally create all the files needed for the tutorial in an argument passed folder. Then we can instruct the user to walk through the tutorial from that folder.

**Comment by guilload** [comment]
I've also been struggling with this. This makes reusing index configurations more difficult. So I vote to get rid of `index_id` and `index_uri` in `IndexConfig` and pass them explicitly in the `quickwit index create` command.
