### ISSUE TITLE
Disable sorting the doc id index.

### ISSUE THREAD

**Issue by fmassot** [quickwit-inc/quickwit#908]
For the 0.2 release, it seems that it is wise to postpone to the next release the configuration of index sorting. 

Pros:
- we don't want the user to pay extra cost for sorting as there are no clear usage of it today

Cons:
- as @PSeitz there is one thing that we lose: it is the compression of the sorted fast field values. We have no pressure coming from users for that right now, so this is reasonable to delay index sorting to the next release.

**Comment by fmassot** [comment]
@PSeitz you have this one too :)

**Comment by fmassot** [comment]
@PSeitz you have this one too :)

**Comment by fulmicoton** [comment]
@fmassot @PSeitz I think we should keep it but remove it from documentation and most importantly default configurations.

**Comment by fmassot** [comment]
Closed by #946
