### ISSUE TITLE
Enforce tag field constraints

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#912]
Right now we only support text tag field with no tokenization (= raw tokenizer).

The reason why we do not handle integer types is just due to the lack of tag generation logic in the packager.
The reason why we do not allow for tokenizer, is because
- they might generate a lot of string
- the tokenizers that have some normalization logic (lowercasing, stemming, etc.) would require a treatment different for all splits, preventing the pruning to happen in the root node.

**Comment by fmassot** [comment]
> The reason why we do not handle integer types is just due to the lack of tag generation logic in the packager.
I'm not sure to understand that point. Currently, a tag is a concatenated string `tag_field:tag_value` where `tag_value` is a string representation of the typed value. What do you mean by `handling integer types`?

**Comment by fulmicoton** [comment]
Right now the packager code just tries to interpret the term dictionary
bytes as utf8.

It truncates the result if it is not possible.

For integer, the values are big endian encoded over 8 bytes.

As a result, we generate pretty weird tags.

Generally speaking we want a unit test too.

Le ven. 17 déc. 2021 à 17:33, François Massot ***@***.***> a
écrit :
