### ISSUE TITLE
Question: match_tag_field_name

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#913]
We rely on `match_tag_field_name` in the demux code.
Clarify with Francois what is the point of this use and check whether it is compatible with a change in the docmapper.

**Comment by fmassot** [comment]
We want to select splits that can be interesting to demux. When there is no tag value or only one for a given tag field, we don't want to demux the split.

Currently this means that we won't demux splits with more that 1000 values too. We may want to demux them too and in this case we could simply check if there is the tag `!tag_field_name`

**Comment by fmassot** [comment]
I suggest updating the demux policy so that we exclude only splits with `!tag_field_name` from demux operations.

**Comment by fmassot** [comment]
ping @fulmicoton : I can handle it

**Comment by fmassot** [comment]
closed by #1031
