### ISSUE TITLE
Setup nice default config values for easing the use of the CLI

### ISSUE THREAD

**Issue by fmassot** [quickwit-inc/quickwit#915]
Following discussions on #852, here are the modifications I would like to make on the CLI:
Assuming the CLI is run in `$QUICKWIT_HOME` with binary in  `$QUICKWIT_HOME/bin`:
- by default, the CLI fetches a config file in `$QUICKWIT_HOME/config/quickwit.yaml`. If there is no config file there, the user must pass the argument `config-uri`. We could also use an environment variable for that.
- the default `metastore_uri` is `file:///$QUICKWIT_HOME/metastore`
- the default data-dir is `$QUICKWIT_HOME/data`
- the default index uri root dir is `file:///$QUICKWIT_HOME/data/indexes`

With these defaults, a user can untar quickwit package and start like this:

## User story 1: test quickwit locally
- `cd quickwit-{VERSION}`
- `./bin/quickwit index create --index-id gh-archive`
- `./bin/quickwit index ingest --index-id gh-archive --input-path ./tutorials/gh-archive/gh-archive.json`
- `./bin/quickwit service run searcher`

## User story 2: test quickwit with index data on s3
- `./bin/quickwit index create --index-id gh-archive --index-uri s3://....`

## User story 3: test quickwit with PostgreSQL metastore
The user edit `./config/quickwit.yaml` with the right `metastore_uri`
- `./bin/quickwit index create --index-id gh-archive --index-uri s3://....`

Or the user has another config file with the right `metastore_uri` and do
- `./bin/quickwit index create --index-id gh-archive --config-uri ./config/postgresql-quickwit.yaml`

**Comment by fulmicoton** [comment]
`${QUICKWIT_HOME}` is defined as $BINARY_PATH/../ 
Confs act as template, and we interpolate them as we read them so that 
the conf can refer to the ${QUICKWIT_HOME} path.
