### ISSUE TITLE
local storage only works if we have only one node

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#919]
Right now we can use file:// to use the local file system as our storage.
That's fine and very useful... However, it fails miserably if we use quickwit with more than one node. We should have some kind of warning about that.

**Comment by fmassot** [comment]
The only use case where we have multiple nodes is search. As search is read-only, I'm not sure to see where it can fail.
Can you be more accurate?

**Comment by fulmicoton** [comment]
Create an index with a metastore on postgresql and with a storage on the current file system.
Index stuff.
Start two search nodes. Get sometime a success, sometime a failure depending on which node you hit.

This is problem we might be able to fix with documentation and warning.

**Comment by fmassot** [comment]
> Start two search nodes. Get sometime a success, sometime a failure depending on which node you hit.

Which kind of failure? Are you indexing stuff and in the meantime making queries?

**Comment by fulmicoton** [comment]
No I mean this is two nodes. One of them won't have the data on its hard disk.

**Comment by fulmicoton** [comment]
Closing as it is a duplicate of #1067
