### ISSUE TITLE
Conjunction by default?

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-inc/quickwit#924]
Tantivy interprets several keywords as a disjunction (OR) by default. 

This makes sense in a document search setting where ranking is supposed to save the day.
This is  a setting where user want the top 10 best documents, and they are fine if the count of matched is pretty useless.

For logs however, people usually use full text search as a filter.
Conjunction would be a more sensible default setting.

(People can still express disjunction using boolean keywords)

**Comment by fmassot** [comment]
My 2 cents. 
What people would expect in general is a disjunction. I think this is the default in elastic too. I would stick to disjunction as it is a standard.

**Comment by fmassot** [comment]
@fulmicoton ping

**Comment by fulmicoton** [comment]
Elasticsearch has a parameter called default_operator that defaults to OR. This is the default for any text-search where you really want to avoid zero result page.

For logs however, it makes no sense, especially with time-ranking and with no aggregation. Sumo logic for instance defaults to AND.

E.g.
You are ranking by time. You type two words. What do you expect to show up as you type indexing error?

**Comment by fmassot** [comment]
yes for log, you're right. 

Let's do the conjunction by default, I don't think this will change the game right now anyway. I suspect that this kind of thing is better handled by the user interface.
