### ISSUE TITLE
Using uri with `file://` use relative paths and may be confusing for a user

### ISSUE THREAD

**Issue by fmassot** [quickwit-inc/quickwit#933]
I'm in favor of interpreting `file://` as `file:///`.

I used the CLI with `file://my-metastore-uri` and did not understand immediately that it created a bunch of directories in my current working directory.

**Comment by fulmicoton** [comment]
ok for that.

**Comment by guilload** [comment]
I'm not too fond of implicit behaviors. I'd rather throw an error if the path is not explicitly made relative with `.` (or `..`) or absolute with `/`.

**Comment by fulmicoton** [comment]
This is fixed. The behavior is centraliized in the Uri struct.
