### ISSUE TITLE
Question: why not having `IndexConfig`directly in the `IndexMetadata` ?

### ISSUE THREAD

**Issue by fmassot** [quickwit-inc/quickwit#968]
Currently, we have this:

```
pub struct IndexMetadata {
    /// Index ID, uniquely identifies an index when querying the metastore.
    pub index_id: String,
    /// Index URI, defines the location of the storage that holds the split files.
    pub index_uri: String,
    /// Checkpoint relative to a source or a set of sources. It expresses up to which point
    /// documents have been indexed.
    pub checkpoint: Checkpoint,
    /// Describes how ingested JSON documents are indexed.
    pub doc_mapping: DocMapping,
    /// Configures various indexing settings such as commit timeout, max split size, indexing
    /// resources.
    pub indexing_settings: IndexingSettings,
    /// Configures various search settings such as default search fields.
    pub search_settings: SearchSettings,
    /// Data sources.
    pub sources: Vec<SourceConfig>,
    /// Time at which the index was created.
    pub create_timestamp: i64,
    /// Time at which the index was last updated.
    pub update_timestamp: i64,
}
```

I think we can keep the `IndexConfig` here instead of having separately all its attributes as we have no more `index_id` and `index_uri` in it.

Moreover, it can be useful for validation purposes to keep things together. `SearchSettings` depends on `DocMapping`.

**Comment by guilload** [comment]
Yeah, crossed my mind too. I'm not overly bothered by this though. The flattening is actually kinda nice and avoids having to do `index.metadata().index_config.indexing_settings`. 

There's also still a chance `IndexMetadata` and `IndexConfig` diverge eventually and we would have to revert such a change. Let's sleep on it?

**Comment by fmassot** [comment]
Agreed, let's keep it like this for now.

**Comment by fmassot** [comment]
I think we can close it as this should be part of a broader discussions on config / doc mapper refactoring.
