### ISSUE TITLE
Update docker image

### ISSUE THREAD

**Issue by evanxg852000** [quickwit-inc/quickwit#972]
Update docker images to new install layout with config files
- https://github.com/quickwit-inc/quickwit/blob/main/Dockerfile
- https://github.com/quickwit-inc/quickwit/blob/main/docker/Dockerfile

**Comment by guilload** [comment]
Do we need the second image? You can use the first one to build release images.

**Comment by evanxg852000** [comment]
The `docker/Dockerfile` was created for our first release, is based on alpine and make use of our installer. because it uses our installer, It automatically installs the musl version and does so with both x86_64 and arm64. Right now if we want to achieve this with, we need cross-build externally and then copy the correct binary.

IMHO, i would keep `./Dockerfile` for making images that push on to nightly or something similar for our ouwn tests. But `docker/Dockerfile` for prod release. 
Because of this issue we even have these files:
- .github/workflows/publish_main_docker_image.yaml
- .github/workflows/publish_release_docker_image.yaml

@guilload  WDYT
