### ISSUE TITLE
Fix tests on indexing pipeline spawn retry

### ISSUE THREAD

**Issue by fmassot** [quickwit-inc/quickwit#999]
These tests relies on `metastore.expect_index_metadata()` but it's not used when the pipeline is spawned. Maybe it was the case before the indexing server. The problem is that these tests did not fail. I will fix that by introducing a new variable to observe: `generation` and will make an assert on that.

**Comment by guilload** [comment]
nit: I'd go with num `num_attempts`.

**Comment by fmassot** [comment]
@guilload currently, we are logging the variable `generation` to indicate that, thus this choice. 

I'm not fond of `num_attempts`, what do you think of `num_pipeline_spaws` which conveys more information?

**Comment by fmassot** [comment]
Mmm, I understand what you meant, you actually want to put the retry count. In this case, we could have both `num_attempts` and `generation` which are 2 different things.

**Comment by fmassot** [comment]
My last take, I would keep `generation` to avoid introducing now a new observable variable that tracks the retry count.

**Comment by fmassot** [comment]
closed by #993
